### PR TITLE
GH-1754: Force headless mode, use chromium & experimental setting to prevent X server

### LINKED ISSUE #1754: Build fails without X
The build is failing on CI because there is no X nor Xvfb [an X server that can run on machines with no display hardware](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml).

But it does build otherwise so the RM can produce an release.

Replicate:
```
ssh -x localhost
cd .../jena-fuseki-ui
mvn clean install
```

Workaround: (same as #1644)
```
                         <configuration>
                            <!-- Fails if there is no TTY -->
                            <testFailureIgnore>true</testFailureIgnore>
                            <environmentVariables>
                                <PORT>${org.apache.jena.fuseki.ui.port}</PORT>
                                <FUSEKI_PORT>${org.apache.jena.fuseki.port}</FUSEKI_PORT>
                            </environmentVariables>
                            <arguments>run test:e2e</arguments>
                        </configuration>
```

<details>
<summary>maven output</summary>

```
[INFO] --- frontend-maven-plugin:1.12.1:yarn (yarn run test:e2e) @ jena-fuseki-ui ---
[INFO] Running 'yarn run test:e2e' in /home/afs/ASF/afs-jena/jena-fuseki2/jena-fuseki-ui
[INFO] yarn run v1.22.17
[INFO] $ concurrently --names 'SERVER,CLIENT,TESTS' --prefix-colors 'yellow,blue,green' --success 'first' --kill-others 'yarn run serve:fuseki' 'yarn wait-on http://localhost:${FUSEKI_PORT}/ping && yarn run dev' 'yarn wait-on http-get://localhost:${PORT}/index.html && cypress run ${0}'
[INFO] [CLIENT] $ /home/afs/ASF/afs-jena/jena-fuseki2/jena-fuseki-ui/node_modules/.bin/wait-on http://localhost:44225/ping
[INFO] [TESTS] $ /home/afs/ASF/afs-jena/jena-fuseki2/jena-fuseki-ui/node_modules/.bin/wait-on http-get://localhost:39529/index.html
[INFO] [SERVER] $ nodemon src/services/mock/json-server.js
[INFO] [SERVER] [nodemon] 2.0.20
[INFO] [SERVER] [nodemon] to restart at any time, enter `rs`
[INFO] [SERVER] [nodemon] watching path(s): *.*
[INFO] [SERVER] [nodemon] watching extensions: js,mjs,json
[INFO] [SERVER] [nodemon] starting `node src/services/mock/json-server.js`
[INFO] [SERVER] JSON Server is running
[INFO] [SERVER] HEAD /ping 200 1.038 ms - 257
[INFO] [CLIENT] $ vite
[INFO] [CLIENT] 
[INFO] [CLIENT]   VITE v4.0.4  ready in 239 ms
[INFO] [CLIENT] 
[INFO] [CLIENT]   ➜  Local:   http://localhost:39529/
[INFO] [CLIENT]   ➜  Network: use --host to expose
[INFO] [SERVER] GET /index.html 200 0.501 ms - 257
[INFO] [TESTS] Your system is missing the dependency: Xvfb
[INFO] [TESTS] 
[INFO] [TESTS] Install Xvfb and run Cypress again.
[INFO] [TESTS] 
[INFO] [TESTS] Read our documentation on dependencies for more information:
[INFO] [TESTS] 
[INFO] [TESTS] https://on.cypress.io/required-dependencies
[INFO] [TESTS] 
[INFO] [TESTS] If you are using Docker, we provide containers with all required dependencies installed.
[INFO] [TESTS] 
[INFO] [TESTS] ----------
[INFO] [TESTS] 
[INFO] [TESTS] Error: spawn Xvfb ENOENT
[INFO] [TESTS] 
[INFO] [TESTS] ----------
[INFO] [TESTS] 
[INFO] [TESTS] Platform: linux-x64 (Ubuntu - 22.10)
[INFO] [TESTS] Cypress Version: 12.4.1
[INFO] [TESTS] yarn wait-on http-get://localhost:${PORT}/index.html && cypress run ${0} exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [SERVER] yarn run serve:fuseki exited with code SIGTERM
[INFO] --> Sending SIGTERM to other processes..
[INFO] [CLIENT] yarn wait-on http://localhost:${FUSEKI_PORT}/ping && yarn run dev exited with code SIGTERM
[INFO] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
```

</details>

### PR DESCRIPTION
**Pull request by kinow**
GitHub issue resolved #1754

Pull request Description:

Also includes a commit to fix `yarn run test:e2e`. I used the env vars for coverage (that calls e2e tests), but forgot to include it for e2e tests when called by itself.

----

 - [ ] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [ ] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kinow** [comment]
I think this should fix the issue, but I couldn't reproduce it locally. Will see if I can trigger Jenkins to run from this PR or from my branch?

**Comment by kinow** [comment]
Hmmm, had a look at ASF's Jenkins, I can see the error, but the job is not parametrized. How do you test PR's or branches with Jenkins, @afs?

**Comment by afs** [comment]
I pulled the branch, did a `ssh -x`.

The yarn.lock file is out of date.

Even fixing that, completely clearing out node_modules and running `yarn install`:
``
[INFO] [TESTS] [FAILED] /home/afs/.cache/Cypress/12.5.1/Cypress/Cypress: bad option: --no-sandbox
[INFO] [TESTS] [FAILED] /home/afs/.cache/Cypress/12.5.1/Cypress/Cypress: bad option: --smoke-test
[INFO] [TESTS] [FAILED] /home/afs/.cache/Cypress/12.5.1/Cypress/Cypress: bad option: --ping=842
```

**Comment by kinow** [comment]
>The yarn.lock file is out of date.

Weird, I'm on this branch and I get no  changes

```bash
$ yarn install
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.52s.
$ git status
On branch headless1
Your branch is up to date with 'kinow/headless1'.

nothing to commit, working tree clean
```

>Even fixing that, completely clearing out node_modules and running yarn install:

Really strange. I deleted my `node_modules` folder, then did a `yarn install`... no changes in `git status`. If you'd like to compare versions:

```bash
$ yarn -v
1.22.5
$ node -v
v16.19.0
```

**Comment by afs** [comment]
Pulling the PR branch:

`package.json` is 956cb17611 (19 hours ago)
`yarn.lock` is 10f9205902 (2 weeks ago)

I have yarn 1.22.19
I have node 18.13.0

**Comment by kinow** [comment]
Upgraded node, and then ran `yarn install`.

```
 node -v
v18.14.0
```

No difference in `package.json`.

Then upgraded `yarn` too (I wasn't aware of [`corepack`](https://yarnpkg.com/getting-started/install) in yarn!)

```
$ yarn -v
1.22.19
```

Removed the `yarn.lock` and then it finally upgraded to the latest versions :grimacing: 

Tried forcing headless mode, but made no difference. Interesting…

**Comment by kinow** [comment]
Ah, ok. So we are not crazy. The Cypress bug about headless requiring xvfb is this one https://github.com/cypress-io/cypress/issues/6012.

It was closed but pointing to a new bug, as it looks like Electron is the one that's requiring the X server: https://github.com/cypress-io/cypress/issues/3899

This last issue is still open, so not much to do for now, unless we start an X server in the Jenkins job, @afs?

**Comment by kinow** [comment]
(or downgrade Cypress... I've upgraded all the dependencies before finding these issues in Cypress, so I will push it to this branch too anyway :shrug: )

**Comment by afs** [comment]
> This last issue is still open, so not much to do for now, unless we start an X server in the Jenkins job, @afs?

We can put back the "don't fail build if e2e fails" setting.

It is working properly when there is graphics. So while it is a visual check, we aren't blocked. CI on the rest of the system works and personally I don't look at the automation logs until the run goes red.

**Comment by kinow** [comment]
The cypress bug is now fixed, https://github.com/apache/jena/pull/1755#issuecomment-1428675379, but I haven't tested it yet.

#1679 has further fixes & improvements to the Cypress configuration. Once that one is merged, I will rebase this one merging the configuration changes.

This is more of a nice-to-have for developers. So we don't have to hurry on this for the upcoming release.

**Comment by kinow** [comment]
Ah, looked at the wrong issue linked in this PR. The Cypress bug is still open, so nothing to do here: https://github.com/cypress-io/cypress/issues/3899. Rebased this PR anyway.

**Comment by kinow** [comment]
Just tested https://github.com/apache/jena/issues/1754 and the issue is not happening. Closing this for now :+1:

**Pull request closed without merging**
