### PR TITLE
GH-2265: Group dependabot patches updates

### LINKED ISSUE #2265: Group dependabot patch updates
### Change

Reduce the number of individual PRs.

Side-effect - groups of patch updates can be tested together by pulling a single PR.

### Are you interested in contributing a pull request for this task?

Yes

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #2265

----

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Good idea! :laughing:

**Comment by kinow** [comment]
I think the only downside will be if we have a single PR with 5-10 dependencies, and the build fails, then someone will have to go through logs, and try to enable/disable the updates until we understand what can or cannot be updated. But not a big deal, I think.

**Review by rvesse — APPROVED** [review]

**Comment by afs** [comment]
@kinow - yes - there are pros and cons. 

So far, for x.x.1 patches, the npm eco-system they seem quite good at semver for patches.

While the wave of JS dependencies seems to be subsiding having caught up, combined mvn+npm is generating a significant stream. I've been testing each PR prior to merging. Having a combined one is actually better in the sense that all the patches get tested together.

Probably should do this for maven as well. PR updated.

**Review by kinow — APPROVED** [review]
+1 for the maven group too. Thanks @afs!

**Review by rvesse — APPROVED** [review]

**Pull request merged**
