### PR TITLE
Unify versions

### PR DESCRIPTION
**Pull request by afs**
Includes a fix for the build of jena-maven-tools.

"jena-parent" renamed to "jena-project" to avoid any version number issues.

### CODE REVIEW

**Comment by kinow** [comment]
Will check out the pull request locally later today just to check what's the output of `mvn clean package`, but change looks good! Thanks!!!

**Comment by ajs6f** [comment]
Ditto what @kinow says (except I will try on July 10).

**Comment by kinow** [comment]
Successfully built the project, within the normal time (30 minutes for`mvn clean install` in order to build all modules, not only those listed under the `dev` profile). Build looks good.

Then used the following to look for some of the artefacts generated.

```
find . -maxdepth 4 -name target -type d -exec find {} -maxdepth 1 -type f \( -iname \*.war -o -iname \*.jar -o -iname \*.ear -o -iname \*.gz -o -iname \*.zip \) \; | grep -v sources | grep -v javadoc | grep -v tests | grep -v distribution | awk -F'/' '{print $NF}' | sort | uniq
```

Here's the output:

```
apache-jena-3.4.0-SNAPSHOT.tar.gz
apache-jena-3.4.0-SNAPSHOT.zip
apache-jena-fuseki-3.4.0-SNAPSHOT.tar.gz
apache-jena-fuseki-3.4.0-SNAPSHOT.zip
jena-arq-3.4.0-SNAPSHOT.jar
jena-base-3.4.0-SNAPSHOT.jar
jena-cmds-3.4.0-SNAPSHOT.jar
jena-core-3.4.0-SNAPSHOT.jar
jena-csv-3.4.0-SNAPSHOT.jar
jena-elephas-common-3.4.0-SNAPSHOT.jar
jena-elephas-io-3.4.0-SNAPSHOT.jar
jena-elephas-mapreduce-3.4.0-SNAPSHOT.jar
jena-elephas-stats-3.4.0-SNAPSHOT-hadoop-job.jar
jena-elephas-stats-3.4.0-SNAPSHOT.jar
jena-fuseki1-3.4.0-SNAPSHOT.jar
jena-fuseki1-3.4.0-SNAPSHOT-server.jar
jena-fuseki-basic-3.4.0-SNAPSHOT.jar
jena-fuseki-basic-3.4.0-SNAPSHOT-server.jar
jena-fuseki-core-3.4.0-SNAPSHOT.jar
jena-fuseki-embedded-3.4.0-SNAPSHOT.jar
jena-fuseki-server-3.4.0-SNAPSHOT.jar
jena-fuseki-war-3.4.0-SNAPSHOT.war
jena-iri-3.4.0-SNAPSHOT.jar
jena-jdbc-core-3.4.0-SNAPSHOT.jar
jena-jdbc-driver-bundle-3.4.0-SNAPSHOT.jar
jena-jdbc-driver-mem-3.4.0-SNAPSHOT.jar
jena-jdbc-driver-remote-3.4.0-SNAPSHOT.jar
jena-jdbc-driver-tdb-3.4.0-SNAPSHOT.jar
jena-maven-tools-3.4.0-SNAPSHOT.jar
jena-osgi-3.4.0-SNAPSHOT.jar
jena-osgi-features-3.4.0-SNAPSHOT.jar
jena-permissions-3.4.0-SNAPSHOT-example.jar
jena-permissions-3.4.0-SNAPSHOT.jar
jena-querybuilder-3.4.0-SNAPSHOT.jar
jena-rdfconnection-3.4.0-SNAPSHOT.jar
jena-sdb-3.4.0-SNAPSHOT.jar
jena-shaded-guava-3.4.0-SNAPSHOT.jar
jena-spatial-3.4.0-SNAPSHOT.jar
jena-tdb-3.4.0-SNAPSHOT.jar
jena-text-3.4.0-SNAPSHOT.jar
jena-text-es-3.4.0-SNAPSHOT.jar
original-jena-fuseki-server-3.4.0-SNAPSHOT.jar
original-jena-jdbc-driver-bundle-3.4.0-SNAPSHOT.jar
original-jena-shaded-guava-3.4.0-SNAPSHOT.jar
```

The parent pom.xml is setting the version to `3.4.0-SNAPSHOT`, and everything else seems to be using that version :tada: Kudos!!!

LGTM

Bruno

**Comment by afs** [comment]
Thanks for the reviews and testing so quickly. It is now in the codebase and we have some time to see how it works out.

**Pull request merged**
