### PR TITLE
jena-ontapi module

### LINKED ISSUE #2160: Support for OWL2
Jena provides support for OWL1 in the OntAPI and partial support for OWL1 reasoning.

This issue is for work any work adding support for OWL2 and [OWL2 profiles](https://www.w3.org/TR/owl2-profiles/) QL, RL,EL

* Add support for some or all of the [RDF syntax for OWL2](https://www.w3.org/TR/owl2-mapping-to-rdf/) to the [Jena ontology API](https://jena.apache.org/documentation/ontology/).
* Add partial support for OWL2 reasoning ([OWL2 RDF Semantics](https://www.w3.org/TR/owl2-rdf-based-semantics/)) to the [current OWL coverage](https://jena.apache.org/documentation/inference/index.html#OWLcoverage) for OWl1.

Support in the ontology API on its own would assist in creating and managing  ontologies.

### PR DESCRIPTION
**Pull request by sszuev**
GitHub issue resolved #2160

Pull request Description:

----

 - [x] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by afs** [comment]
Good to see this!

I've let the PMC know this PR exists.
https://lists.apache.org/thread/yr9q394fssr0mvgxvrskynmhjlz0g33x

Firstly - thank you for making clear the origins.

Secondly - this is a significant addition to Jena so there'll need a software grant at some point to keep everything neat and tidy. This is routine. I'm mentioning it now so you know it's coming.
https://www.apache.org/licenses/contributor-agreements.html#grants

```
The original code is taken from [ONT-API](https://github.com/owlcs/ont-api).
```
Who "owns" that project? Is it Manchester University?

How much of the is code you personally have written and how much is code written by someone else?

For code you wrote, it doesn't matter whether that was via `owlcs/ont-api` or not. It is as if you are contributing directly.

How much of this PR is code others have written, and for significant amounts, are they aware and agree that you are making this contribution? This is more than licensing - the Apache Software Foundation does not get involved in "hostile forks".

From what I can see @ignazio1977 has been a significant contributor.

**Comment by sszuev** [comment]
> Who "owns" that project? Is it Manchester University?
> 
> How much of the is code you personally have written and how much is code written by someone else?
> 
> For code you wrote, it doesn't matter whether that was via `owlcs/ont-api` or not. It is as if you are contributing directly.
> 
> How much of this PR is code others have written, and for significant amounts, are they aware and agree that you are making this contribution? This is more than licensing - the Apache Software Foundation does not get involved in "hostile forks".
> 
> From what I can see @ignazio1977 has been a significant contributor.

The code is 100% mine.

Actually, I have nothing to do with the Manchester University. 
Initially, ONTAPI project was made in the domain of 'avicomp' organization (now this organization is not in github anymore, and, maybe legal organization does not exist as well). 
When I stopped working with 'avicomp', I needed a new home for the project, and I opened the issue https://github.com/owlcs/owlapi/issues/889  

At some point in time, I needed to duplicate some of the functionality of the original OWL-API-impl, and I copied the related commits, just as I copied the commits from my repository ([jena-owl2](https://github.com/sszuev/jena-owl2)) to this PR. That's why ONT-API has many contributors, although in fact the only contributor is me: the original owlcs team do not work directly on ONT-API.

The copied part is a purely OWL-API, for example a class
https://github.com/owlcs/ont-api/blob/3.x.x/src/main/java/com/github/owlcs/ontapi/owlapi/axioms/AnnotationAssertionAxiomImpl.java 
The copied commits are not related to the `OntModel`, which is in this PR: they are about the implementation of OWLAPI-api, i.e. related to ONT-API itself (`OntModel` was designed as underlying model, there are no OWLAxioms, since the ONT-API itself - at top level - is responsible for OWLAxioms)

Thus, I am the only contributor of this PR.

**Comment by ignazio1977** [comment]
I can confirm the statements above.
Patch set is too large for me to go through, but the OWLAPI project doesn't have any Jena references, so I believe all the code here has been developed outside the Manchester university, and just hosted under the owlcs "organisation", which is not part of Manchester university anyway - the original members were Manchester university phd students or postdocs.

I can't comment about the code origin, but it's certainly not a hostile fork - or, indeed, a fork - as far as OWLAPI and Manchester university are concerned.

Cheers,
I.

**Comment by namedgraph** [comment]
Are there any changes for OWL 1 users?

**Comment by sszuev** [comment]
> Are there any changes for OWL 1 users?

New `OntModel` supports all features of old model, including OWL1. Old ("legacy") `OntModel` is untouched, it can be marked as deprecated later.

**Comment by afs** [comment]
All looks good for moving forward with this. There are some process steps necessary; the code, apart from license headers and Eclipse issues noted below, looks good.

**1. Licenses**

All the java files and the POM file need the Apache license header for contributed code. The text is not the same as a 3rd party use of the Apache license.

The attached bash script [`fixlicense`](https://github.com/apache/jena/files/15143404/fixlicense.txt) (instructions in the file) will fixup the java. (`.txt` added to make it accepted to GH upload). The POM file needs the same comment at the top as `jena-arq/pom.xml`.

It's important that these are done before the code is added to the Jena codebase. The project can't make changes in order to accept a contribution.

**2. build**

At the top level,

```
    mvn clean install
```

should run. After fixing the license issues above, and after rebasing to current main, it does for me.

**3. Code (compile)**

While it builds using maven, but fails in Eclipse IDE. It looks like the eclipse compiler does not handle generics in the same way as OpenJDK. The attached file [pr2420-eclipse.txt](https://github.com/apache/jena/files/15143468/pr2420-eclipse.txt) contains a diff for building in Eclipse and with maven.

**4. Javadoc**

There are javadoc warnings. Some relate to IntelliJ as they look like specific items but are quite a few incorrect javadoc.

Under Eclipse: 293 javadoc errors.

With maven: 45 javadoc errors including about `@inheritDoc` and `com.github.sszuev.jena.ontapi.vocabulary`.

When working with the whole codebase, for example, during a release, it's very useful to have as clean a build as practical so it is easy to see new warnings appearing.

**5. ICLA** (Individual Contributors License Agreement)

This is a significant contribution. we need an ICLA on-file.

The form and instructions are available at

https://www.apache.org/licenses/contributor-agreements.html#clas

https://www.apache.org/licenses/icla.pdf

Having read the [intellectual property clearance process](https://incubator.apache.org/ip-clearance/index.html) and looked at the list of previous contributions in the Foundation, I don't now think we need a Software Grant. We would if there was an owning organsiation involved, but as @ssvuev would be signing both, nothing is gained.

Taking into account the code origin discussion here on the PR, please remove the mention "The original code" sentence in README.md. If you want to credit the inspiration or ideas, please feel free to.

**6. Prepare for merge**

It would be useful if you could rebase the PR to current `main`.

For incorporating into the Jena codebase, we don't need all the development commits.

My preference is that the PR in squashed to a single commit, with mesage like "GH-2160: ...".  I didn't see any groups of related commits that would be useful to keep together. It's better to do the suqash on the PR, not via github "squash and merge" so that it is merged into Jena exactly as contributed.

**7. PMC VOTE**

When it's ready, we'll have a formal VOTE on dev@jena to show the PMC is aware and agrees to what is going on.

**8. Documentation - jena-site**

At some point, not necessarily before merging the code, the Jena website will need at least one page describing the new ontapi.  If nothing else, something the release can point to and about how user can migratre code to using the new module. How much of the existing documentation still applies (except for the java package name).

**Comment by sszuev** [comment]
> At the top level, `mvn clean install` should run. After fixing the license issues above, and after rebasing to current main, it does for m

I see ARQ tests are failing.
revision 221f30c0e5968e49d7db5c9d4057c64082f153f3
openjdk 17.0.10 2024-01-16
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   Datasets not isomorphic
[ERROR]   Datasets not isomorphic
[ERROR]   Datasets not isomorphic
[ERROR]   Graphs not isomorphic
[ERROR]   Graphs not isomorphic
[ERROR]   Graphs not isomorphic
[ERROR]   Graphs not isomorphic
[ERROR]   Graphs not isomorphic
[ERROR]   Graphs not isomorphic
[INFO]
[ERROR] Tests run: 17575, Failures: 9, Errors: 0, Skipped: 2
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Jena 5.1.0-SNAPSHOT:
[INFO]
[INFO] Apache Jena ........................................ SUCCESS [01:24 min]
[INFO] Apache Jena - IRI .................................. SUCCESS [ 13.549 s]
[INFO] Apache Jena - Base ................................. SUCCESS [ 25.756 s]
[INFO] Apache Jena - Core ................................. SUCCESS [09:21 min]
[INFO] Apache Jena - ARQ .................................. FAILURE [04:05 min]
[INFO] Apache Jena - ONTAPI ............................... SKIPPED
[INFO] Apache Jena - SHACL ................................ SKIPPED
[INFO] Apache Jena - ShEx ................................. SKIPPED
[INFO] Apache Jena - RDF Patch ............................ SKIPPED
[INFO] Apache Jena - RDF Connection ....................... SKIPPED
[INFO] Apache Jena - DBOE Database Operation Environment .. SKIPPED
[INFO] Apache Jena - DBOE Base ............................ SKIPPED
[INFO] Apache Jena - DBOE Transactions .................... SKIPPED
[INFO] Apache Jena - DBOE Indexes ......................... SKIPPED
[INFO] Apache Jena - DBOE Index test suite ................ SKIPPED
[INFO] Apache Jena - DBOE Transactional Datastructures .... SKIPPED
[INFO] Apache Jena - DBOE Storage ......................... SKIPPED
[INFO] Apache Jena - TDB1 (Native Triple Store) ........... SKIPPED
[INFO] Apache Jena - TDB2 (Native Triple Store) ........... SKIPPED
[INFO] Apache Jena - Libraries POM ........................ SKIPPED
[INFO] Apache Jena - Command line tools ................... SKIPPED
[INFO] Apache Jena - SPARQL Text Search ................... SKIPPED
[INFO] Apache Jena - GeoSPARQL Engine ..................... SKIPPED
[INFO] Apache Jena - Fuseki - A SPARQL 1.1 Server ......... SKIPPED
[INFO] Apache Jena - Fuseki Core Engine ................... SKIPPED
[INFO] Apache Jena - Fuseki UI ............................ SKIPPED
[INFO] Apache Jena - Fuseki Data Access Control ........... SKIPPED
[INFO] Apache Jena - Fuseki Server Main ................... SKIPPED
[INFO] Apache Jena - Fuseki Server Jar .................... SKIPPED
[INFO] Apache Jena - Fuseki Webapp ........................ SKIPPED
[INFO] Apache Jena - Fuseki WAR File ...................... SKIPPED
[INFO] Apache Jena - Fuseki Server Standalone Jar ......... SKIPPED
[INFO] Apache Jena - Fuseki Docker Tools .................. SKIPPED
[INFO] Apache Jena - Fuseki Binary Distribution ........... SKIPPED
[INFO] Apache Jena - Integration Testing .................. SKIPPED
[INFO] Apache Jena - Benchmark Suite ...................... SKIPPED
[INFO] Apache Jena - Benchmarks Shaded Jena 4.8.0 ......... SKIPPED
[INFO] Apache Jena - Benchmarks JMH ....................... SKIPPED
[INFO] Apache Jena - BOM .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:33 min
[INFO] Finished at: 2024-04-29T14:16:50+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project jena-arq: There are test failures.
[ERROR]
[ERROR] Please refer to /mnt/c/work/owlcs/ext/jena/jena-arq/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jena-arq
```

**Comment by afs** [comment]
I'm not seeing those failures.  I don't think I've see the build fail in this way.

Which tests are failing?

There are github actions in the project. There is a Linux build.

My working copy of this PR is:
https://github.com/afs/jena/tree/pr2420-ontapi
This has the java fixes and the license headers change.

The Windows build on github is a bit iffy but it fails later (randomly, and is affected by time-of-day) in Fuseki with local networking issues. I believe it is related to JUnit clean-up after a test suite has run.

**Comment by sszuev** [comment]
> I'm not seeing those failures. I don't think I've see the build fail in this way.
> 
> Which tests are failing?
> 
> There are github actions in the project. There is a Linux build.
> 
> My working copy of this PR is: https://github.com/afs/jena/tree/pr2420-ontapi This has the java fixes and the license headers change.
> 
> The Windows build on github is a bit iffy but it fails later (randomly, and is affected by time-of-day) in Fuseki with local networking issues. I believe it is related to JUnit clean-up after a test suite has run.

this is a CRLF/LF (Windows/Linux newline) problem. `.gitattributes` can help make the build platform independent.
But that's not relevant to this issue. With `:jena-ontapi` tests everything is ok.

image

**Comment by sszuev** [comment]
1,2,3,4,5,6 - done

**Comment by afs** [comment]
The build is looking good.

This
```
[INFO] Running org.apache.jena.ontapi.OntClassMiscTest
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
is fixed by having 
```
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j2-impl</artifactId>
      <scope>test</scope>
    </dependency>
``` 
in the POM and a `log4j2-test.properties` or `log4j2.properties` file in src/test/resources. A copy of `jena-arq/src/tets/resources/log4j2.properties` will do.

**Comment by afs** [comment]
I'm getting warning from Eclipse - not the maven build - here are the non-javadoc ones. Mostly about missing `@Override`:

```
The import java.util.HashSet is never used
    OntClassMiscTest.java	/jena-ontapi/src/test/java/org/apache/jena/ontapi	line 35
The method clearHasKeys() of type OntClass.Named should be tagged with @Override since it actually overrides a superinterface method
    OntClass.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 1074
The method getModel() of type OntResource should be tagged with @Override since it actually overrides a superinterface method
    OntResource.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 40
The method ranges() of type OntRelationalProperty should be tagged with @Override since it actually overrides a superinterface method
    OntRelationalProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 59
The method removeDisjointClass(Resource) of type OntClass.Named should be tagged with @Override since it actually overrides a superinterface method
    OntClass.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 1058
The method removeDomain(Resource) of type OntAnnotationProperty should be tagged with @Override since it actually overrides a superinterface method
    OntAnnotationProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 122
The method removeEquivalentClass(Resource) of type OntClass.Named should be tagged with @Override since it actually overrides a superinterface method
    OntClass.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 1066
The method removeRange(Resource) of type OntAnnotationProperty should be tagged with @Override since it actually overrides a superinterface method
    OntAnnotationProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 130
The method removeSuperClass(Resource) of type OntClass.Named should be tagged with @Override since it actually overrides a superinterface method
    OntClass.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 1050
The method subProperties() of type OntRelationalProperty should be tagged with @Override since it actually overrides a superinterface method
    OntRelationalProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 66
The method subProperties(boolean) of type OntAnnotationProperty should be tagged with @Override since it actually overrides a superinterface method
    OntAnnotationProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 44
The method subProperties(boolean) of type OntRelationalProperty should be tagged with @Override since it actually overrides a superinterface method
    OntRelationalProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 42
The method superProperties() of type OntRelationalProperty should be tagged with @Override since it actually overrides a superinterface method
    OntRelationalProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 73
The method superProperties(boolean) of type OntAnnotationProperty should be tagged with @Override since it actually overrides a superinterface method
    OntAnnotationProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 51
The method superProperties(boolean) of type OntRelationalProperty should be tagged with @Override since it actually overrides a superinterface method
    OntRelationalProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 51
The type GraphMem is deprecated
    UnionGraphTest.java	/jena-ontapi/src/test/java/org/apache/jena/ontapi	line 31
Type safety: The method contains(RDFNode) belongs to the raw type RDFNodeList. References to generic type RDFNodeList<E> should be parameterized
    OntRelationalProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 187
Type safety: Unchecked cast from ExtendedIterator<capture#8-of ?> to ExtendedIterator<O>
    OntGraphModelImpl.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/impl	line 189
Type safety: Unchecked cast from Object & OntEntity & AsNamed<?> to O
    OntClassImpl.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects	line 1447

Unlikely argument type for equals(): OntNamedProperty seems to be unrelated to OntRelationalProperty
    OntIndividual.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 189	Java Problem
```

**Comment by afs** [comment]
Javadoc: less of a concern: there are lots of warnings (291) in Eclipse! Very repetitive and possible better seeing if the HTML output is OK anyway.

One class of warning that looks like it needs addressing is: "Invalid param tag name"
```
Javadoc: Invalid param tag name
    CreateClasses.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 195	Java Problem
Javadoc: Invalid param tag name
    CreateClasses.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 244	Java Problem
Javadoc: Invalid param tag name
    ModelTestUtils.java	/jena-ontapi/src/test/java/org/apache/jena/ontapi/testutils	line 141	Java Problem
Javadoc: Invalid param tag name
    ModelTestUtils.java	/jena-ontapi/src/test/java/org/apache/jena/ontapi/testutils	line 171	Java Problem
Javadoc: Invalid param tag name
    OntClass.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 227	Java Problem
Javadoc: Invalid param tag name
    OntModel.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 242	Java Problem
Javadoc: Invalid param tag name
    OntObject.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 107	Java Problem
Javadoc: Invalid param tag name
    SetCardinality.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 35	Java Problem
```
to take the first:
```
    * @param cardinality, {@code int}, non-negative number

```
It's flagging the "`,`" and causes the Eclipse display of javadoc not to have the text.

**Comment by afs** [comment]
The last category of warnings is to do with `@SuppressWarnings` - related to IntelliJ. They can stay.

But one is:

```
Unsupported @SuppressWarnings("ALL")
	TestSpec.java	/jena-ontapi/src/test/java/org/apache/jena/ontapi	line 66	Java Problem
```
which should be "all"

**Comment by sszuev** [comment]
In Intellij Idea I see no warnings, including about javadocs.

But several warnings are real issues.
fixed:
- issue with `@Override`
- issue with comma in javadocs
- unused import in test-class

------
- `The type GraphMem is deprecated
    UnionGraphTest.java	/jena-ontapi/src/test/java/org/apache/jena/ontapi	line 31` - deprecation is suppressed, strange to have this warning from Eclipse
- `Type safety: The method contains(RDFNode) belongs to the raw type RDFNodeList. References to generic type RDFNodeList<E> should be parameterized
    OntRelationalProperty.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 187` - code seems to be ok
- `Unlikely argument type for equals(): OntNamedProperty seems to be unrelated to OntRelationalProperty
    OntIndividual.java	/jena-ontapi/src/main/java/org/apache/jena/ontapi/model	line 189	Java Problem`
I think this is about equals which is inherited from Resource, don't know how it can be fixed
- javadocs. there are no warnings in Intellij Idea, probably I need to install eclipse to see all of them

**Comment by sszuev** [comment]
When generating javadocs using Eclipse I see 100 warnings:
image

some of them like
```
Generating ...\jena-ontapi\doc\org\apache\jena\ontapi\common\EnhNodeFinder.ByPredicate.html...
...\jena-ontapi\src\main\java\org\apache\jena\ontapi\common\EnhNodeFinder.java:119: warning: no comment
        public ByPredicate(Property predicate) {
```
describing each technical class will be a long, but doable task. usually these (auxiliary) classes have meaningful names. all major top-level classes have valid javadocs

**Comment by sszuev** [comment]
> <dependency>
>       <groupId>org.apache.logging.log4j</groupId>
>       <artifactId>log4j-slf4j2-impl</artifactId>
>       <scope>test</scope>
>     </dependency>

There is no logging in the module  `:jena-ontapi`, I tried to avoid extra dependencies (for lib it is important). 
Warning comes from jena-arq

> The build is looking good.
> 
> This
> 
> ```
> [INFO] Running org.apache.jena.ontapi.OntClassMiscTest
> SLF4J: No SLF4J providers were found.
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
> ```
> 
> is fixed by having
> 
> ```
>     <dependency>
>       <groupId>org.apache.logging.log4j</groupId>
>       <artifactId>log4j-slf4j2-impl</artifactId>
>       <scope>test</scope>
>     </dependency>
> ```
> 
> in the POM and a `log4j2-test.properties` or `log4j2.properties` file in src/test/resources. A copy of `jena-arq/src/tets/resources/log4j2.properties` will do.

There is no logging in the module  `:jena-ontapi`, I tried to avoid extra dependencies (for lib it is important). 
Warning comes from jena-arq

**Comment by afs** [comment]
`<scope>test</scope>` means the dependency isn't available or necessary for lib users. JUnit is also scope=test.

```
[desktop]  >>  mvn -Dscope=runtime dependency:tree 
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.apache.jena:jena-ontapi >---------------------
[INFO] Building Apache Jena - ONTAPI 5.1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.6.1:tree (default-cli) @ jena-ontapi ---
[INFO] org.apache.jena:jena-ontapi:jar:5.1.0-SNAPSHOT
[INFO] \- org.apache.jena:jena-arq:jar:5.1.0-SNAPSHOT:compile
[INFO]    +- org.apache.jena:jena-core:jar:5.1.0-SNAPSHOT:compile
[INFO]    |  +- org.apache.jena:jena-base:jar:5.1.0-SNAPSHOT:compile
[INFO]    |  |  +- org.apache.commons:commons-csv:jar:1.10.0:compile
[INFO]    |  |  +- commons-io:commons-io:jar:2.16.1:compile
[INFO]    |  |  +- commons-codec:commons-codec:jar:1.17.0:compile
[INFO]    |  |  +- org.apache.commons:commons-compress:jar:1.26.1:compile
[INFO]    |  |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO]    |  |  +- com.github.ben-manes.caffeine:caffeine:jar:3.1.8:compile
[INFO]    |  |  |  +- org.checkerframework:checker-qual:jar:3.37.0:compile
[INFO]    |  |  |  \- com.google.errorprone:error_prone_annotations:jar:2.21.1:compile
[INFO]    |  |  \- com.github.andrewoma.dexx:collection:jar:0.7:compile
[INFO]    |  +- org.apache.jena:jena-iri:jar:5.1.0-SNAPSHOT:compile
[INFO]    |  \- org.roaringbitmap:RoaringBitmap:jar:1.0.6:compile
[INFO]    +- com.google.code.gson:gson:jar:2.10.1:compile
[INFO]    +- com.apicatalog:titanium-json-ld:jar:1.4.0:compile
[INFO]    +- org.glassfish:jakarta.json:jar:2.0.1:compile
[INFO]    +- com.google.protobuf:protobuf-java:jar:4.26.1:compile
[INFO]    +- org.apache.thrift:libthrift:jar:0.20.0:compile
[INFO]    \- org.apache.commons:commons-lang3:jar:3.14.0:compile
[INFO] ------------------------------------------------------------------------
```

**Comment by afs** [comment]
> When generating javadocs using Eclipse I see 100 warnings:

I must have some turned if if they are the default. Like IntelliJ, the defaults do rather slide into opinions of how code would be.

Many of the "SuppressWarnings" are for what I assume are IntelliJ specific treatment.

I've picked out what I think might be important in the comments above and these are fixed or understood. That's enough.

For me, when the release manager, clean build is important - makes it possible to see when new warnings appear.

Next step is to do a VOTE on the dev@jena mailing list (that's my task). It can be a lazy vote (assumed consensus). That is needs to opne for a few days (to cover some business days, and weekend, and national May holidays). If that parses, merge!

**Review by afs — APPROVED** [review]

**Comment by afs** [comment]
dev@ vote : https://lists.apache.org/thread/gx6s5h00zz5x1d8k5p3g5w6g5x1vg112

**Comment by afs** [comment]
And it is now in the SNAPSHOT builds!
https://repository.apache.org/content/repositories/snapshots/org/apache/jena/jena-ontapi/

and in the whole system for development builds 5.1.0-SNAPSHOT 2024-05-08T07:49:53 Z and later.

This will be the big thing in the 5.1.0 release (mid June?).

Thank you!

**Comment by sszuev** [comment]
writing documentation is a big task. to be able to control the process, I made a draft: https://github.com/apache/jena-site/pull/187

**Comment by sszuev** [comment]
I think, the documentation is ready for review
https://github.com/apache/jena-site/pull/187

**Pull request merged**
