### PR TITLE
Deprecating Map1 in favor of Java8 Function

### PR DESCRIPTION
**Pull request by ajs6f**
Deprecating Map1 in favor of Java8 Function.

I believe I have managed to avoid mangling any public contracts presented by Jena.

### CODE REVIEW

**Comment by afs** [comment]
Looks good but I'm having a problem with {{OntResourceImpl.AsMapper}}.  This is removed in {{OntResourceImpl}] but still in use in {{OntClassImpl}}, {{EnumeratedClassImpl}}, {{BooleanClassDescriptionImpl}}, {{DataRangeImpl}}. Maybe some other changes didn't get committed/pushed?

**Comment by ajs6f** [comment]
Hm. That does sound weird. I'll take a look and straighten it out.

**Comment by afs** [comment]
Created JENA-929 to help track this long-term. Just mention JENA-929 in comments and the JIRA wil be updated automatically.

**Comment by afs** [comment]
Restoring {{AsMapper}} seemed to fix things - at least , it compiled then, just a bunch of warnings about use of {{Map1}} and unused {{java.util.Function}} imports so it does look like a minor sync issue.

**Comment by ajs6f** [comment]
Yep-- Git weirdness. I think that should square it. I'm not mentioning the Jira issue here because Git mistakes don't seem like part of the long-term record.

**Comment by ajs6f** [comment]
Right-- I just amended the commit to fully excise AsMapper.

**Comment by afs** [comment]
Got it - it's clean now.  I remove unused imports, replaced Statement.Util and some Triple statics by rewriting the few uses in place e.g. Statement::getSubject.

**Comment by ajs6f** [comment]
Thanks!

P.S. Sorry about unused imports and the like. That was sloppy.

**Pull request merged**
