### PR TITLE
JENA-1263: Recommended redirect behavior

### PR DESCRIPTION
**Pull request by ajs6f**

### CODE REVIEW

**Comment by acoburn** [comment]
I can confirm that this patch solves the issue related to 303 redirects, outlined in JENA-1263.

**Comment by afs** [comment]
Can this be merged? (hint , hint :-)

**Comment by ajs6f** [comment]
Holy moly I totally lost track of this, I am running out the door but if you don't merge it before tomorrow my time I will tomorrow.

**Comment by afs** [comment]
Too late here now but if nothing happens in the next day or two, I will take your comment as "OK to merge".

**Comment by ajs6f** [comment]
Pushed to Apache git under separate cover

**Pull request closed without merging**
