### PR TITLE
Bump YASQE up to version 2.11.4

### PR DESCRIPTION
**Pull request by kinow**
This should fix JENA-1072. Tested locally.

screenshot_2016-10-10_20-38-20

Basically executed:

```
wget https://github.com/OpenTriply/YASGUI.YASQE/archive/v2.11.4.zip
unzip v2.11.4.zip -d yasqe-2.11.4
cd yasqe-2.11.4/

cp YASGUI.YASQE-2.11.4/dist/yasqe.min.js ~/Development/java/jena/jena/jena-fuseki2/jena-fuseki-core/src/main/webapp/js/lib/
cp YASGUI.YASQE-2.11.4/dist/yasqe.min.js.map ~/Development/java/jena/jena/jena-fuseki2/jena-fuseki-core/src/main/webapp/js/lib/
cp YASGUI.YASQE-2.11.4/dist/yasqe.min.css ~/Development/java/jena/jena/jena-fuseki2/jena-fuseki-core/src/main/webapp/css/
```

YASQE 2.11.4 was released with the fix for the issue in the SPARQL syntax, after merging the pull request https://github.com/OpenTriply/YASGUI.YASQE/pull/89

Sending as a pull request since this updates a library, and could introduce regressions. So in case anyone else would like to test it first, before it is merged and included in the next release, now is the time :-)

Cheers
Bruno

### CODE REVIEW

**Comment by kinow** [comment]
Added a new commit, and edited my comments and title. Now instead of 2.11.3 it is 2.11.4. @LaurensRietveld warned me about a regression in 2.11.3 (big thanks!). 2.11.4 includes the fix to our issue, plus the fix to the regression.

FWIW, looks like the regression in 2.11.3 involved an infinite loop crash in the browser.

**Comment by afs** [comment]
Phew!

Is this ready to merge? From my side, sooner is better as we head towards a release.

**Comment by kinow** [comment]
I think so. Tested locally, validation looks good, performance as well. Haven't had any issues, and the query from JENA-1072 is marked as valid too. If we merge now it might be easier to get other people to play with Fuseki and confirm everything is OK too, before the next release.

**Comment by afs** [comment]
Go for it!

**Comment by kinow** [comment]
Done!

**Pull request closed without merging**
