### PR TITLE
Fixes needed for release v4.7.0 RC2. 

### LINKED ISSUE #1694: Test failures due to Jena initialization in jena-geosparql tests
### Version

4.7.0 RC1

### What happened?

jena-geosparql test suite has an random order failure mode.

https://lists.apache.org/thread/pwb5holpbw5yyrjnkgrlmzohf2yg340r

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #1694

Pull request Description:
* Initialization fix for jena-geosparql tests
* Fix for CrossOriginFilter so it works in tomcat (lucky find!)
* Make the jena-fuseki-geosparql run on a port other than 3030.

----

 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

**Comment by kinow** [comment]
Nice! Testing as soon as I get home to confirm it works on my environment.  Thanks @afs!

**Review by kinow — COMMENTED** [review]
@afs, `mvn clean install` on my laptop (same that failed GeoSparql) passed GeoSparql, failed in JDBC In-Memory Driver:

```bash
[INFO] Apache Jena - GeoSPARQL Engine ..................... SUCCESS [ 21.700 s]
[INFO] Apache Jena - Fuseki with GeoSPARQL Engine ......... SUCCESS [ 13.870 s]
[INFO] Apache Jena - Integration Testing .................. SUCCESS [ 12.228 s]
[INFO] Apache Jena - Distribution ......................... SUCCESS [  3.313 s]
[INFO] Apache Jena - Security Permissions ................. SUCCESS [ 30.920 s]
[INFO] Apache Jena - Extras ............................... SUCCESS [  0.054 s]
[INFO] Apache Jena - Extras - Query Builder ............... SUCCESS [ 12.405 s]
[INFO] Apache Jena - CommonsRDF for Jena .................. SUCCESS [  2.341 s]
[INFO] Apache Jena - Extras - Service Enhancer ............ SUCCESS [ 34.048 s]
[INFO] Apache Jena - Code Examples ........................ SUCCESS [  1.464 s]
[INFO] Apache Jena - JDBC Parent .......................... SUCCESS [  0.019 s]
[INFO] Apache Jena - JDBC Core API ........................ SUCCESS [ 50.136 s]
[INFO] Apache Jena - JDBC Remote Endpoint Driver .......... SUCCESS [ 34.841 s]
[INFO] Apache Jena - JDBC In-Memory Driver ................ FAILURE [02:28 min]
[INFO] Apache Jena - JDBC TDB Driver ...................... SKIPPED
[INFO] Apache Jena - JDBC Driver Bundle ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:57 min
[INFO] Finished at: 2022-12-26T17:11:10+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:jar (default) on project jena-jdbc-driver-mem: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jena/ (java.io.FileNotFoundException: https://jena.apache.org/documentation/javadoc/jena/package-list)
[ERROR] warning: The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/documentation/javadoc/arq/ are in named modules.
[ERROR] 1 error
[ERROR] 1 warning
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/kinow/Development/java/jena/jena/jena-jdbc/jena-jdbc-driver-mem/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jena-jdbc-driver-mem
kinow@ranma:~/Development/java/jena/jena$ 
```

**Comment by afs** [comment]
I think that maven is the final summary - were there more details at the jena-jdbc/jena-jdbc-driver-mem?

`The code being documented uses packages in the unnamed module,` happens a lot - when one modules javadoc refers to another's (seems to be the user of `automatic-module-name`), and it is a warning.

I get:
```
[INFO] --- maven-javadoc-plugin:3.4.1:jar (attach-javadocs) @ jena-jdbc-driver-mem ---
[INFO] No previous run data found, generating javadoc.
[WARNING] Javadoc Warnings
[WARNING] warning: The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/documentation/javadoc/jena/ are in named modules.
[WARNING] warning: The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/documentation/javadoc/arq/ are in named modules.
[WARNING] 2 warnings
```
and the build finishes.

**Comment by afs** [comment]
Aside from finding an unrelated bug in javadoc at jena-iri (building with Java11 and on MS Windows only, causes [MJAVADOC-586/comment](https://issues.apache.org/jira/browse/MJAVADOC-586?focusedCommentId=17410795&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17410795)).

I get a clean build on MacOS github action and local linux.
I am now trying java17, MS Windows as a GH action.

@kinow 
- machine machine/OS are you using?
- do you have the maven log from the `attach-javadocs @ jena-jdbc-driver-mem` step? 

Background: the project has discovered that java11 javadoc is a bit flaky, which is why we build with Java17 targetting java11.

**Comment by kinow** [comment]
Sorry, it's building and re-building for #1679. Going to switch branches in a second and try it again with `-e -X`. But my env is here:

```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/apache-maven-3.8.5
Java version: 17.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-56-generic", arch: "amd64", family: "unix"
```

Ubuntu LTS 22.04.1

**Comment by kinow** [comment]
Righto, checking out this one and will `mvn clean install > log.txt 2>&1` and paste it to paste.apache. It will take a few minutes…

**Comment by afs** [comment]
All very weird! 

And the unrelated #1644 is consistent on the GH action for MS Windows (Java17 JDK) but not the other architectures.

**Comment by kinow** [comment]
Env:

```bash
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/apache-maven-3.8.5
Java version: 17.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-56-generic", arch: "amd64", family: "unix"
```

Git version:

```bash
kinow@ranma:~/Development/java/jena/jena$ git log -n 4
commit 9115eeb8f50ac0ab19e0b74d3661814ebd3703c6 (HEAD -> pr-1695)
Author: Andy Seaborne <andy@apache.org>
Date:   Mon Dec 26 17:05:29 2022 +0000

    Change workflows to full build

commit 080e9e71bc3ecabc88e2f9e1cb2dba220b68de3c
Author: Andy Seaborne <andy@apache.org>
Date:   Mon Dec 26 12:38:44 2022 +0000

    Run jena-fuseki-geosparql tests on a non-default port

commit 28e7e202e42371845635a5e193817fe93034bd61
Author: Andy Seaborne <andy@apache.org>
Date:   Mon Dec 26 12:38:05 2022 +0000

    Jetty independent CrossOriginFilter

commit 120e0ed85b5103b61ca3f4a568171fb766a0c184
Author: Andy Seaborne <andy@apache.org>
Date:   Sun Dec 25 17:28:49 2022 +0000

    GH-1694: Initialization in jena-geosparql
```

Output of `mvn clean install -e -X > log.txt 2>&1` (Eclipse & WebStorm both closed): https://paste.apache.org/cex9s (firefox on my laptop fails to load this tab :disappointed_relieved: )

Rather long, I think all the errors are the same, UnknownHostException, like this at the end of the output:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:28 min
[INFO] Finished at: 2022-12-26T19:49:39+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:jar (attach-javadocs) on project jena-geosparql: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jena/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] error: Error fetching URL: https://jena.apache.org/documentation/javadoc/arq/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] error: Error fetching URL: https://jena.apache.org/documentation/javadoc/tdb/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] error: Error fetching URL: https://jena.apache.org/documentation/javadoc/text/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] error: Error fetching URL: https://jena.apache.org/documentation/javadoc/rdfconnection/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] error: Error fetching URL: https://jena.apache.org/documentation/javadoc/fuseki2/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] error: Error fetching URL: https://jena.apache.org/documentation/javadoc/permissions/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jdbc/ (java.net.UnknownHostException: jena.apache.org)
[ERROR] warning: The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/jena-arq/apidocs/ are in named modules.
[ERROR] 8 errors
[ERROR] 1 warning
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/kinow/Development/java/jena/jena/jena-geosparql/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:jar (attach-javadocs) on project jena-geosparql: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jena/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/arq/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/tdb/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/text/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/rdfconnection/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/fuseki2/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/permissions/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jdbc/ (java.net.UnknownHostException: jena.apache.org)
warning: The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/jena-arq/apidocs/ are in named modules.
8 errors
1 warning

Command line was: /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/kinow/Development/java/jena/jena/jena-geosparql/target/apidocs' dir.

    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:306)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jena/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/arq/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/tdb/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/text/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/rdfconnection/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/fuseki2/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/permissions/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jdbc/ (java.net.UnknownHostException: jena.apache.org)
warning: The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/jena-arq/apidocs/ are in named modules.
8 errors
1 warning

Command line was: /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/kinow/Development/java/jena/jena/jena-geosparql/target/apidocs' dir.

    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.failOnError (AbstractJavadocMojo.java:7103)
    at org.apache.maven.plugins.javadoc.JavadocJar.doExecute (JavadocJar.java:193)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.execute (AbstractJavadocMojo.java:2034)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.reporting.MavenReportException: 
Exit code: 1 - error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jena/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/arq/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/tdb/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/text/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/rdfconnection/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/fuseki2/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/permissions/ (java.net.UnknownHostException: jena.apache.org)
error: Error fetching URL: https://jena.apache.org/documentation/javadoc/jdbc/ (java.net.UnknownHostException: jena.apache.org)
warning: The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/jena-arq/apidocs/ are in named modules.
8 errors
1 warning

Command line was: /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/kinow/Development/java/jena/jena/jena-geosparql/target/apidocs' dir.

    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.doExecuteJavadocCommandLine (AbstractJavadocMojo.java:6092)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeJavadocCommandLine (AbstractJavadocMojo.java:5968)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport (AbstractJavadocMojo.java:2277)
    at org.apache.maven.plugins.javadoc.JavadocJar.doExecute (JavadocJar.java:189)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.execute (AbstractJavadocMojo.java:2034)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jena-geosparql

```

**Comment by kinow** [comment]
Oh, and I can open these links from my browser. No proxy.

**Comment by kinow** [comment]
> All very weird!
> 
> And the unrelated #1644 is consistent on the GH action for MS Windows (Java17 JDK) but not the other architectures.

Huh, that's weird. Could be related to the browser engine on Windows… Chrome & Firefox JS (and even how CSS is handled I think) may differ in each OS/platform.

**Comment by afs** [comment]
`Error fetching link: /home/kinow/Development/java/jena/jena/jena-db/jena-dboe-index-test/target/apidocs. Ignored it.`

This in jena-geosparql seems to be from the Jena pom links section which must have been working in the build to get this far but says: `Temporary failure in name resolution`

But I can't see why it caused the build to stop. The only odd thing is:

```
[DEBUG] Could not follow https://jena.apache.org/documentation/javadoc/jena/. Reason: jena.apache.org: Temporary failure in name resolution
```
:shrug:

**Comment by afs** [comment]
At least your build got past the jena-geosparql test suite running which is the main reason for this PR.

Does running maven offline work for you? `mvn -o clean install`

At this point, I'm inclined to spend a bit more time on it but it is now looking like external factors. Those get addressed by finding finding a setup that "happens to work" rather than a deep reason and isn't guaranteed to work for everyone.

So if it can be tweaked, great, but otherwise I think it is better to get the release done.

We need more information from more environments and the way to get that is ask people to run the development codebase.

**Comment by kinow** [comment]
Yeah, I suspect it could be related to my Internet connection, somehow. I am on a 4G mobile network for another few weeks (jumping between hotels). While the connection is really good, and I can watch movies, run Docker, Maven, etc, I don't know how well it works, nor if it has some limits.

You pointed to a previous error that could be due to name resolution in this mobile network too.

And this command has just succeeded @afs (the second time, the first it failed): `mvn clean install -DpreferIPv4Stack` (found searching that error message you mentioned, from this SO https://stackoverflow.com/questions/45868239/api-api-ai-temporary-failure-in-name-resolution).

Now I am trying a `mvn clean install` without that networking property (looking at the JVM networking settings doc page, I think I had to include the java.net prefix https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/doc-files/net-properties.html :man_shrugging: )

**Comment by kinow** [comment]
Will try the offline build soon.

>So if it can be tweaked, great, but otherwise I think it is better to get the release done.
>
>We need more information from more environments and the way to get that is ask people to run the development codebase.

+1

I also have another Ubuntu laptop from $work. I can try building on that laptop using mobile 4G, and another day I can try using the $work networking (a national research center, should be reliable I think).

**Comment by afs** [comment]
Also `mvn clean install -Dmaven.javadoc.skip=true` after all we publish the javadoc! and if you work with the source jars, you don't need the javadoc artifacts.

**Comment by kinow** [comment]
`mvn clean install` now succeeded for me (still using this branch, same env).

`mvn clean install -o` also succeeded.

>Also mvn clean install -Dmaven.javadoc.skip=true after all we publish the javadoc! and if you work with the source jars, you don't need the javadoc artifacts.

I might forget that. I normally just `mvn` and `cd` into `fuseki-ui` when doing something on the UI.

But maybe that could be used to test a release? If so we can include that in the email sent so others don't have to build it locally either.

**Pull request merged**
