### PR TITLE
Jena5

### LINKED ISSUE #2019: System Upgrades
* Java17
* Use jakarta.servlet
* slf4j 2.xx series

* BOM
* SBOM

### LINKED ISSUE #2020: Jena5 Node Changes
Changes to Node and related classes (RDF Terms)

* Simplify type hierarchy
* `LiteralLabel`:
  * Convert to class
  * Restrict use to Node implementation.
  * Make it terms centric.
  * Eager and lazy forms for value calculation
* Remove BlankNodeId redirection in Node_Blank
* Remove partial, incomplete RDF 1.0 support

### LINKED ISSUE #2021: Jena5 Model API changes
* Remove deprecated classes and methods
* Remove unused code: 
* Simplify container iterators
* Remove reification support
* Remove isXML/isWellFormed from APIs
* Remove "ModelExtract" - `TripleBoundary`, `StatementBoundary`, `GraphExtract`, `ModelExtract`
* Remove `RDFReaderF.getReader()` and `RDFWriter.getWriter()`
* Remove `ResourceF`
* Remove `Selector` and `Model.query(Selector)`

### LINKED ISSUE #2022: Remove deprecated classes and methods
Remove code that has been marked deprecated for one or more releases and is not used by the Jena codebase.

### LINKED ISSUE #2023: Remove support for JSON-LD 1.0
Continue to provide JSON-LD 1.1 using [Titanium](https://github.com/filip26/titanium-json-ld).

Remove use of [jsonld-java](https://github.com/jsonld-java/jsonld-java) which provides JSON-LD 1.0.

### LINKED ISSUE #2024: Upgrade to Jetty12
The Jena5 code base was first updated from Jetty10 to Jetty11. This is the javax.servlet to jakarta.servlet change and it is only chnage of packages.

Then switch to using Jetty12 which involves code changes because Jetty12 is a different architecture to Jetty11.

### LINKED ISSUE #2025: RRX: New RDF/XML parser
The RRX parser replaces ARP as the default choice of RDF/XML parser in RIOT.

RRX is specially for parsing RDF/XML files, not general RDF/XML processing. It is more maintainable.

The ARP code remains in the code base with special `Lang` constants.

### LINKED ISSUE #2026: Move ModelMaker to the Ontology API package
The OntAPI is the only user of `ModelMaker`.

### LINKED ISSUE #2027: Remove unused assemblers
Remove assemblers related to core features that are no longer used or exposed to applications.

### LINKED ISSUE #2028: Deprecate use of initial binding
"InitialBinding" is only available in some query/update execution - it is not available for remote execution.

It is replaced by "substitution" which is rewriting the query or update within the caller client. This can be applied to any query/update executions, including remote calls.

### LINKED ISSUE #2032: Rename TDB1 artifact jena-tdb to jena-tdb1

### LINKED ISSUE #2033: Move package tree org.apache.jena.tdb to org.apache.jena.tdb1.
Move TDB1 so that it does not occupy the unversioned `tdb` pattern name.

Rename `org.apache.jena.tdb` as `org.apache.jena.tdb1`.

Rename classes in the new area to `TDB1*`.

Leave redirection stubs in `org.apache.jena.tdb`.

### LINKED ISSUE #2035: Retire jena-jdbc
dev@ email https://lists.apache.org/thread/nr1o03ny1l53yqplbhzoj2nc6hosco7r

Some of the final updating will have to be done after Jena5 becomes the main development line because we normally record the commit id ion `archived-modules.md`.

The Jena site will also need updating at Jena5.

The jena-jdbc code has been updated for Jena5/jetty12 - the security tests pass.

### LINKED ISSUE #2036: Incorporate the rdf-tables and expiring-map code in Jena GeoSPARQL.
Jena's GeoSPARQL support relies on two Apache-licensed packages [rdf-tables](https://github.com/galbiston/rdf-tables) and [expiring-map](https://github.com/galbiston/expiring-map).

These package were last released Jan 29, 2019

galbiston has done a fantastic job on GeoSPARQL.

Some of the Jena5 changes (TDB1 renames) impact these packages and dependency version differences have "just happened to work".

It seems safer to incorporate the code from these two packages into Jena's codebase so that they track Jena.

Put under `org.apache.jena.ext.io.github.galbiston....` which makes it easily reversible.

(The expiring map can probably be replaced by a Caffeine cache with entry expiry.)

### LINKED ISSUE #2037: Use PREFIX and BASE in Turtle output by default.
PREFIX and BASE were defined for Turtle and Trig in RDF 1.1 (2014).

The RDF 1.2 working group is changing many examples from `@prefix` and `@base` to `PREFIX ` and `BASE`.

Jena 5.x should use `PREFIX` and `BASE` by default.

(NB Please enclose any use of `@` in a comment enclosed by backticks so it is not a github notification)

### LINKED ISSUE #2038: Switch default in-memory graph from value indexing to term indexing.
Traditionally, Jena has provided value semantics in memory graphs (and hence memory models) for a limited, fixed set of datatypes.

i.e. the triple `:s :p 0.5` matches the `:s :p 0.500`.

This indexing carries a cost in the memory foot print, in access costs and in complexity of the `GraphMem` implementation of the `Graph` interface, regardless of whether it used or not.

Other graph implementations with term-semantics are already available in Jena (see `GraphMemFactory`).

Values written via the API are canonicalised on input and when searched for so this change is not visible in that situation.

TDB is different - this issue does not related to TDB1 or TDB2.

This issue is for switching the default behaviour of Jena5 to "same term". 
There would be a system switch to set "same-value" semantics.

### LINKED ISSUE #2040: Remove support for ARQ script functions in Python (jython)
While JavaScript has seen usage, Python has not.

Jython is Python2.

The scripting support in ARQ is "any language the JDK script manager can provide, suitably configured". It also carries a cost because of security issues that arise from having a general purpose programming language inside the query engine.

Remove support for Python and focus effort on JavaScript.

### PR DESCRIPTION
**Pull request by afs**
This is a pull request for the Jena5 cycle with issues as noted in the commit messages.

It is _not_ for merging into main. 

The best way forward is probably to create a "jena5" branch for now, keeping "main" as Jena 4.x.x until quite near to release Jena5 in some form.

To be safe, I've created the "jena5" branch and targeted this PR at it. This reduces the chance of accidentally getting material onto "main".

There is more work to do but this would give everyone a chance to see what is proposed and also contribute their own changes.

closes #2019  closes #2020  closes #2021  closes #2022  closes #2023
closes #2024  closes #2025  closes #2026  closes #2027  closes #2028
closes #2029  closes #2032  closes #2033  closes #2035  closes #2036
closes #2037  closes #2038  closes #2040

----

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
image

:eyes: probably one of the largest PR's I've seen here. Thanks for preparing it!

**Comment by afs** [comment]
Can't manually link to more than 10 issues (github limit) so having to use "close NNNN" in the description.

**Comment by afs** [comment]
This is about as ready as it'll ever be.  

The PR is now term-graph by default for in-memory graphs. While that sounds a huge change, it seems to have less less impact than might be expected. The in-memory transactional dataset is term-based in Jena4. The change does not affect TDB1 or TDB2 so Fuseki use is mostly unchanged.

Output in Turtle etc uses PREFIX and BASE by default.

There is more to do - one area is language tag handling #2039.

**Comment by namedgraph** [comment]
A per-feature PRs would be easier to review 😬

**Comment by afs** [comment]
https://github.com/apache/jena/issues?q=is%3Aissue+is%3Aopen+label%3AJena5

**Pull request merged**
