### PR TITLE
rdfdiff fixes

### PR DESCRIPTION
**Pull request by william-vw**
GitHub issue resolved #

Pull request Description:

What I believe are some fixes for rdfdiff so it works for some of my test cases (unsure whether it will work for all cases, though).

----

 - [X] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [ ] Commits have been squashed to remove intermediate development commit messages.
 - [ ] Key commit messages start with the issue number (GH-xxxx, or if in JIRA, JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rvesse** [comment]
Could you please describe the bugs this PR is fixing?

I can't see what those are from reading the PR diff.  There's a lot of whitespace change in this PR as well which makes understanding what's changed very difficult even with Hide Whitespace mode enabled so describing what's actually changed would be useful.

From what I can follow you are changing the output format which I don't think we'd want to do because that potentially breaks all existing users of this tool.  The current output format is intentionally following classic `diff` style.  Perhaps consider putting the alternative output format behind a new flag/option so we retain backwards compatibility while allowing users like yourself to opt into a newer output format?

**Comment by afs** [comment]
Ping @william-vw

**Comment by afs** [comment]
Ping @william-vw

**Comment by william-vw** [comment]
@afs apologies, I'm lacking the cycles these days to properly format this PR so I will close it for now.

**Comment by afs** [comment]
I completely understand!

It can be reopened.

**Pull request closed without merging**
