### PR TITLE
No stacktrace on regex errors.  Cancel/close during sorting.

### PR DESCRIPTION
**Pull request by afs**
Changes for:

"runtime regex pattern and many many log messages"
https://lists.apache.org/thread.html/0d6042871739323716346ebfff76e64ede7c39a52eacbc0ab17d6d3c@%3Cdev.jena.apache.org%3E

"Bug in SortedDataBag?"
https://lists.apache.org/thread.html/be3ecf8f41b03a747f6bab78a072ca55b2ea1a07a6d7ae1e53600ac5@%3Cdev.jena.apache.org%3E

### CODE REVIEW

**Comment by ehedgehog** [comment]
Whoops, clicked too soon. 

In E_Regex.eval, we Log.warn(this,message). I see that using Log.warn would be
inappropriate, since it acts globally and would switch off all logging of whatever
we chose as a key, but as per the original problem it would be useful to
suppress identical log lines.

I wondered about replacing the Log.warn with

String m = ex.getMessage();
            	if (!m.equals(currentFailMessage)) {
            		currentFailMessage = m;
            		Log.warn(this, m); 
            	}

catching the case where the same pattern error keeps occuring.
This might be either of overkill or underkill.

Chris

**Comment by afs** [comment]
This PR covers the "Bug in SortedDataBag?" report as well.  Waiting on tests for that.

**Comment by ehedgehog** [comment]
I realised that there were no test cases for QueryIterTopN, which has
a failure mode like TestQuerySort. I added three tests to QueryIterSort
(because I reused the CallbackIterator from TestQueryIterSort and 
extracting that to a new file would make the diffs more complicated)
in the same style as the tests for QueryIterSort.close():

================================================

    @Test public void testTopNCloseClosesSource() {
		
		long numItems = 3;
		boolean distinct = false;
        Context context = new Context() ;
    	ExecutionContext ec = new ExecutionContext(context, (Graph) null, (DatasetGraph) null, (OpExecutorFactory) null);

		QueryIterTopN tn = new QueryIterTopN(iterator, comparator, numItems, distinct, ec);
		tn.close();
		assertTrue(iterator.isClosed());
	}
    
    @Test public void testTopNExhaustionClosesSource() {
		
		Callback nullCB = new Callback() { @Override public void call() {} };
		iterator.setCallback(nullCB);
		
		long numItems = 3;
		boolean distinct = false;
        Context context = new Context() ;
    	ExecutionContext ec = new ExecutionContext(context, (Graph) null, (DatasetGraph) null, (OpExecutorFactory) null);

		QueryIterTopN tn = new QueryIterTopN(iterator, comparator, numItems, distinct, ec);
		while (tn.hasNext()) tn.next();
		assertTrue(iterator.isClosed());
	}
    
    @Test public void testTopNCancelClosesSourceIterator() {
				
		long numItems = 3;
		boolean distinct = false;
        Context context = new Context() ;
    	ExecutionContext ec = new ExecutionContext(context, (Graph) null, (DatasetGraph) null, (OpExecutorFactory) null);

		QueryIterTopN tn = new QueryIterTopN(iterator, comparator, numItems, distinct, ec);
		try {
			while (tn.hasNext()) tn.next();
			fail("QueryCancelledException not caught");
		} catch (QueryCancelledException q) {
			assertTrue("cancellation did not close source iterator", iterator.isClosed());			
		}
    }

==========================================

It turns out that the third of these tests fails because an exception
thrown during QueryIterTopN's initializeIterator does not close
the source (or any other) iterator. So I wrapped the body of the
initializeIterator in a try-catch-QueryCancelledException and closed
both the initializeIterator nad the QueryIterTopN.
===============================================

   private Iterator<Binding> sortTopN(final QueryIterator qIter, final Comparator<Binding> comparator) {
        return new IteratorDelayedInitialization<Binding>() {
            @Override
            protected Iterator<Binding> initializeIterator() {
            	try {
            		while ( qIter.hasNext() ) {
	                    Binding binding = qIter.next() ;
	                    if ( heap.size() < limit )
	                        add(binding) ;
	                    else {
	                        Binding currentMaxLeastN = heap.peek() ;
	                        if ( comparator.compare(binding, currentMaxLeastN) < 0 )
	                            add(binding) ;
	                    }
	                }
	                qIter.close() ;
	                Binding[] y = heap.toArray(new Binding[]{}) ;
	                heap = null ;
	                Arrays.sort(y, comparator) ;
	                return asList(y).iterator() ;
	            } catch (QueryCancelledException e) {
	            	QueryIterTopN.this.close();
	            	this.close();
	            	throw e;
	            }
            }
        } ;
    }

================================================
 The new tests now pass.

**Comment by ehedgehog** [comment]
Sorry for the layout mess.

**Comment by afs** [comment]
Split into PR#238 (regex) and PR#239 (cancel sort)

**Pull request closed without merging**
