### PR TITLE
GH-1924: Add a "long" Turtle format variant

### PR DESCRIPTION
**Pull request by rybesh**
This resolves: #1924

Pull request Description:

Adds a "long" Turtle format variant based on rdflib's "longturtle" format. It uses a fixed indentation width (2) and linebreaks after each sequence element.

See related `users@jena` ML discussion: https://lists.apache.org/thread/0x2j11zs8vj1pv130hrlqxws4myl908v

I’m not sure how to test this—there do not seem to be any current tests for indentation.

----

 - [ ] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [X] Commits have been squashed to remove intermediate development commit messages.
 - [ ] Key commit messages start with the issue number (GH-xxxx, or if in JIRA, JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by afs** [comment]
I've added an issue to track this.

Could you please put "GH-1924: " on the front of the git log message?

**Comment by afs** [comment]
> I’m not sure how to test this—there do not seem to be any current tests for indentation.

The most important testing is round-trip of data: `TestRiotWriterGraph` and `TestTurtleWriter` `TestTurtleWriterPretty` (there are two `TestTurtleWriter` - I don't know why).

**Comment by afs** [comment]
Documentation: https://jena.apache.org/documentation/io/rdf-output.html

Source:
https://github.com/apache/jena-site/blob/main/source/documentation/io/rdf-output.md

**Comment by afs** [comment]
The enum `IndentStyle` and class `TurtleWriterLong` seem to be missing.

**Comment by rybesh** [comment]
I should be able to add the missing files, docs and tests tomorrow.

**Comment by afs** [comment]
Great. 4.9.0 is "soon", not "very soon" (having to find time means we can't give accurate dates).

Documentation changes can be after release - we update the site as needed, not just on release.

**Comment by rybesh** [comment]
Moved to https://github.com/apache/jena/pull/1925

**Pull request closed without merging**
