### PR TITLE
JENA-1221: Embedded Fuseki server

### PR DESCRIPTION
**Pull request by afs**
This add a new module under jena-fuseki2 for running Fuseki embedded.

It is a new module so it can have it's own POM. The POM excludes all unecessary dependencies from jena-fuseki-core including logging provider, and modules jena-text and jena-spatial.

### CODE REVIEW

**Comment by afs** [comment]
Examples:
```
    /** Create a SPARQL endpoint for an application dataset and start the server */ 
    private static void example0() {
        DatasetGraph dsg = dataset() ;
        // Run a Fuseki server with "/ds" as the dataset.
        // Default set up : query, update, graph store and quads operations. 
        FusekiEmbeddedServer.make(3330, "/ds", dsg).start() ;
    }
```
```
    /** Create a SPARQL endpoint for an application dataset */ 
    private static void example1() {
        DatasetGraph dsg = dataset() ;
        // Run a Fuseki server with "/ds" as the dataset.
        // Default set up : query, update, graph store and quads operations. 
        FusekiEmbeddedServer server = FusekiEmbeddedServer.create()
            .setPort(3333)
            .add("/ds", dsg) 
            .build() ;
        server.start() ;
    }
```
```
    /** Create a Fuseki server with a just a SPAQRL query endpoint.
     * The SPARQL endpoint URLs look like {@code /rdf/sparql?query=}
     */
    private static void example2() {
        DatasetGraph dsg = dataset() ;

        DataService queryService = new DataService(dsg) ;
        queryService.addEndpoint(OperationName.Query, "sparql");
        
        FusekiEmbeddedServer server = FusekiEmbeddedServer.create()
            .setPort(3334)
            .add("/rdf", queryService)
            .build() ;
        server.start() ;
        // Sync with the server - this is blocking.
        server.join() ;
    }
```
```    
    /** Create a Fuseki server with two sets of services. One is the usual set of read-only endpoints,
     *  the other is just being able to do quads operations
     * GET, POST, PUT on  "/ds2" in N-quads and TriG.
     */
    private static void example3() {
        DatasetGraph dsg = DatasetGraphFactory.createTxnMem() ;

        // A service with just being able to do quads operations
        // That is, GET, POST, PUT on  "/ds2" in N-quads and TriG. 
        DataService dataService = new DataService(dsg) ;
        dataService.addEndpoint(OperationName.Quads_RW, "");

        FusekiEmbeddedServer server = FusekiEmbeddedServer.create()
            .setPort(3335)
            .add("/ds2", dataService)
            .build() ;
        server.start() ;
    }
```
```    
    /** Create a Fuseki server with some services on the dataset URL. */
    private static void example4() {
        DatasetGraph dsg = DatasetGraphFactory.createTxnMem() ;

        // A service able to do quads operations and SPARQL query
        DataService dataService = new DataService(dsg) ;
        dataService.addEndpoint(OperationName.Quads_RW, "");
        dataService.addEndpoint(OperationName.Query, "");

        FusekiEmbeddedServer server = FusekiEmbeddedServer.create()
            .setPort(3336)
            .add("/data", dataService)
            .build() ;
        server.start() ;
    }
```
```    
    /** Create a Fuseki server by reading a configuration file. */
    private static void example5() {
        FusekiEmbeddedServer server = FusekiEmbeddedServer.create()
            .setPort(3337)
            // Defines /ds
            .parseConfigFile("config.ttl")
            .build() ;
        server.start() ;
    }
```

**Comment by afs** [comment]
Example of the application sharing the dataset with Fuseki. This also shows using java.util.logging for application and embedded Fuseki.

```
public static void example6() {
        LogCtl.setJavaLogging();
        Logger LOG = LoggerFactory.getLogger("example6") ;
        DatasetGraph dsg = DatasetGraphFactory.createTxnMem() ;
        FusekiEmbeddedServer server = FusekiEmbeddedServer.make(3330, "/ds", dsg) ;
        server.start() ;
        
        LOG.info("Remote 1") ;
        try (QueryExecution qExec = 
            QueryExecutionFactory.sparqlService("http://localhost:3330/ds/query", "SELECT * { ?s ?p ?o}") ) {
            // Empty table
            QueryExecUtils.executeQuery(qExec); 
        }

        // Transaction-protected update.
        Txn.execWrite(dsg,  ()->{
            Quad q = SSE.parseQuad("(_ :s :p _:b)") ;
            dsg.add(q); 
        }) ;
        
        LOG.info("Remote 2") ;
        try (QueryExecution qExec = 
            QueryExecutionFactory.sparqlService("http://localhost:3330/ds/query", "SELECT * { ?s ?p ?o}") ) {
            // One row.
            QueryExecUtils.executeQuery(qExec); 
        }
        server.stop() ;
    }
```

**Comment by kinow** [comment]
Lurking around this issue.

I'm setting up a SPARQL database with Jena in Jenkins

https://github.com/biouno/database-sparql-plugin/blob/master/src/main/java/org/biouno/databasesparql/JenaTDBDatabase.java

Used TDB and Jena JDBC. 

If I understand correctly, this new module will allow me to expose the database via SPARQL. Looking forward to it!

**Comment by afs** [comment]
Yes, that's the idea!

**Comment by afs** [comment]
Draft documentation:
https://gist.github.com/afs/c5e025e55a1d9773f323bb050e4d9d39

**Pull request merged**
