### PR TITLE
JENA-1058: ASCIIFoldingLowerCaseKeywordAnalyzer for jena-text

### PR DESCRIPTION
**Pull request by osma**
See https://issues.apache.org/jira/browse/JENA-1058

### CODE REVIEW

**Comment by osma** [comment]
The class names are getting ridiculously long, but I just followed the same pattern as before.

**Comment by afs** [comment]
+1 : Looks good

By the way - is there documentation (i.e. a list) of all the analyzers we have?

**Comment by osma** [comment]
@afs Yes there is, in the jena-text documentation, though calling it a list is a bit of a stretch since there are only four currently (StandardAnalyzer,  SimpleAnalyzer, KeywordAnalyzer and LowerCaseKeywordAnalyzer) and only LowerCaseKeywordAnalyzer is specific to jena-text, the other three come directly from Lucene.

See https://jena.apache.org/documentation/query/text-query.html#configuring-an-analyzer 

About this PR: I think I will try to implement a more generic, configurable analyzer, as suggested by Claude Warren in a comment on JIRA-1058. If it's not too difficult, it would obviously be better than this very specific analyzer.

**Comment by osma** [comment]
I drop this in favor of JENA-1062 / PR #97

**Pull request closed without merging**
