### PR TITLE
Changes to jena-elephas to update it for RIOT/RDFParser changes.

### PR DESCRIPTION
**Pull request by afs**
This PR is some changes to  jena-elephas, around I/O, to keep it in step with the evolution of RIOT.

### CODE REVIEW

**Comment by afs** [comment]
The main change is gradual removal of `ParserProfile` to be replaced by a builder pattern around `RDFPaserBuilder`.

At this point, the use of pull parsing (N-Quads and N-Triple parers as iterators) is not done so this PR is not yet ready to merge but is available for initial review.

This has been a useful exercise to validate the `RDFParser` design and it shows that the design needs to cope with the iterator-parsing style.

**Comment by afs** [comment]
Ping/FYI @rvesse.

**Comment by rvesse** [comment]
Thanks for starting on this, one of the first things I thought of when you started on the API improvements was that it would make life much easier for components like Elephas that need to manipulate the parser set up

Looks great so far

**Comment by afs** [comment]
This has become multi-purpose.

To clear up Elephas, some intended widespread clear up in RIOT is necessary to avoid doing changes twice.

Therefore, this PR has general RIOT evolution and also Elephas changes (in separate commits).

**Comment by afs** [comment]
This is now complete.

The build full passes.

**Comment by afs** [comment]
Now recorded as JENA-1315.

https://issues.apache.org/jira/browse/JENA-1315

**Pull request merged**
