### PR TITLE
JENA-1409: jena-db testing

### PR DESCRIPTION
**Pull request by afs**
Covers [JENA-1406](https://issues.apache.org/jira/browse/JENA-1406), PR #295

### CODE REVIEW

**Comment by afs** [comment]
This PR configures surefire to run the `TC_*` test suite in each of the modules doing disk-based tests. This should make the tests non-parallel.

Also includes checking in `TestProcessFileLock`.

**Comment by kinow** [comment]
Tested this pr on Win 10

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T07:39:06+12:00)
Maven home: C:\Users\kinow\Development\java\apache-maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_144\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

Had the same test as yesterday.

```
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in org.apache.jena.dboe.base.file.TestMetaFile
Running org.apache.jena.dboe.base.file.TestProcessFileLock
Tests run: 7, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.013 sec <<< FAILURE! - in org.apache.jena.dboe.base.file.TestProcessFileLock
process_lock_2(org.apache.jena.dboe.base.file.TestProcessFileLock)  Time elapsed: 0.003 sec  <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:58)
Caused by: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:56)

process_lock_3(org.apache.jena.dboe.base.file.TestProcessFileLock)  Time elapsed: 0 sec  <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:58)
Caused by: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:56)

process_lock_4(org.apache.jena.dboe.base.file.TestProcessFileLock)  Time elapsed: 0 sec  <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:58)
Caused by: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:56)

process_lock_5(org.apache.jena.dboe.base.file.TestProcessFileLock)  Time elapsed: 0 sec  <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:58)
Caused by: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:56)

process_lock_6(org.apache.jena.dboe.base.file.TestProcessFileLock)  Time elapsed: 0 sec  <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:58)
Caused by: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:56)

process_lock_7(org.apache.jena.dboe.base.file.TestProcessFileLock)  Time elapsed: 0.001 sec  <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:58)
Caused by: java.io.IOException: Access is denied
        at org.apache.jena.dboe.base.file.TestProcessFileLock.beforeTest(TestProcessFileLock.java:56)

Running org.apache.jena.dboe.base.file.TestSegmentedMemBuffer
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.apache.jena.dboe.base.file.TestSegmentedMemBuffer
Running org.apache.jena.dboe.base.record.TestRecord
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.jena.dboe.base.record.TestRecord
Running org.apache.jena.dboe.base.recordfile.TestRecordBufferPage
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.apache.jena.dboe.base.recordfile.TestRecordBufferPage

Results :

Tests in error:
  TestProcessFileLock.beforeTest:58 ▒ RuntimeIO java.io.IOException: Access is d...
  TestProcessFileLock.beforeTest:58 ▒ RuntimeIO java.io.IOException: Access is d...
  TestProcessFileLock.beforeTest:58 ▒ RuntimeIO java.io.IOException: Access is d...
  TestProcessFileLock.beforeTest:58 ▒ RuntimeIO java.io.IOException: Access is d...
  TestProcessFileLock.beforeTest:58 ▒ RuntimeIO java.io.IOException: Access is d...
  TestProcessFileLock.beforeTest:58 ▒ RuntimeIO java.io.IOException: Access is d...

Tests run: 156, Failures: 0, Errors: 6, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache Jena - Project .............................. SUCCESS [  2.116 s]
[INFO] Apache Jena - Shadowed external libraries .......... SUCCESS [  2.116 s]
[INFO] Apache Jena - IRI .................................. SUCCESS [  9.749 s]
[INFO] Apache Jena - Base Common Environment .............. SUCCESS [ 13.158 s]
[INFO] Apache Jena - Core ................................. SUCCESS [01:11 min]
[INFO] Apache Jena - ARQ (SPARQL 1.1 Query Engine) ........ SUCCESS [01:31 min]
[INFO] Apache Jena - RDF Connection ....................... SUCCESS [  7.471 s]
[INFO] Apache Jena - TDB (Native Triple Store) ............ SUCCESS [ 36.030 s]
[INFO] Apache Jena - Database Operation Environment ....... SUCCESS [  0.281 s]
[INFO] Apache Jena - DBOE Base ............................ FAILURE [  2.099 s]
[INFO] Apache Jena - DBOE Transactions .................... SKIPPED
[INFO] Apache Jena - DBOE Indexes ......................... SKIPPED
[INFO] Apache Jena - DBOE Index test suite ................ SKIPPED
[INFO] Apache Jena - DBOE Transactional Datastructures .... SKIPPED
[INFO] Apache Jena - TDB2 ................................. SKIPPED
[INFO] Apache Jena - Libraries POM ........................ SKIPPED
[INFO] Apache Jena - Command line tools ................... SKIPPED
[INFO] Apache Jena - SPARQL Text Search ................... SKIPPED
[INFO] Apache Jena - SPARQL Text Search - Elasticsearch ... SKIPPED
[INFO] Apache Jena - SPARQL Spatial Search ................ SKIPPED
[INFO] Apache Jena - Fuseki - A SPARQL 1.1 Server ......... SKIPPED
[INFO] Apache Jena - Fuseki Server Engine ................. SKIPPED
[INFO] Apache Jena - Fuseki Embedded Server ............... SKIPPED
[INFO] Apache Jena - Fuseki WAR File ...................... SKIPPED
[INFO] Apache Jena - Fuseki Server Standalone Jar ......... SKIPPED
[INFO] Apache Jena - Fuseki Basic Server .................. SKIPPED
[INFO] Apache Jena - Fuseki Binary Distribution ........... SKIPPED
[INFO] Apache Jena - Integration Testing .................. SKIPPED
[INFO] Apache Jena - Distribution ......................... SKIPPED
[INFO] Apache Jena - Fuseki1 .............................. SKIPPED
[INFO] Apache Jena - Data Tables for RDF and SPARQL ....... SKIPPED
[INFO] Apache Jena - SDB (SQL based triple store) ......... SKIPPED
[INFO] Apache Jena - Maven Plugins, including schemagen ... SKIPPED
[INFO] Apache Jena - Security Permissions ................. SKIPPED
[INFO] Apache Jena - Extras ............................... SKIPPED
[INFO] Apache Jena - Extras - Query Builder ............... SKIPPED
[INFO] Apache Jena - JDBC Parent .......................... SKIPPED
[INFO] Apache Jena - JDBC Core API ........................ SKIPPED
[INFO] Apache Jena - JDBC Remote Endpoint Driver .......... SKIPPED
[INFO] Apache Jena - JDBC In-Memory Driver ................ SKIPPED
[INFO] Apache Jena - JDBC TDB Driver ...................... SKIPPED
[INFO] Apache Jena - JDBC Driver Bundle ................... SKIPPED
[INFO] Apache Jena - Elephas .............................. SKIPPED
[INFO] Apache Jena - Elephas - Common API ................. SKIPPED
[INFO] Apache Jena - Elephas - I/O ........................ SKIPPED
[INFO] Apache Jena - Elephas - Map/Reduce ................. SKIPPED
[INFO] Apache Jena - Elephas - Statistics Demo App ........ SKIPPED
[INFO] Apache Jena - OSGi ................................. SKIPPED
[INFO] Apache Jena - OSGi bundle .......................... SKIPPED
[INFO] Apache Jena - OSGi Karaf features .................. SKIPPED
[INFO] Apache Jena ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:56 min
[INFO] Finished at: 2017-10-27T10:24:57+13:00
[INFO] Final Memory: 77M/1012M
[INFO] ------------------------------------------------------------------------
```

**Comment by afs** [comment]
What I don't get is why PR #295 passes `TestProcessFileLock` (or does it?) as it changes `TestDatabaseOps`.

Here 5 failures has become 6. This is good! They are all the `beforeTest` now.

For `TestProcessFileLock`, `@Rule` will be fine as its low space impact.

**Comment by kinow** [comment]
>What I don't get is why PR #295 passes TestProcessFileLock (or does it?) as it changes TestDatabaseOps.

That was on my Linux environment at home only, sorry. Testing on Windows now.

**Comment by kinow** [comment]
Still have those other errors in Windows. Not sure, however, if the errors I had in Linux and in Windows are related. Will try to debug at least one test today before going home.

**Pull request merged**
