### PR TITLE
allow geo index search for literals

### PR DESCRIPTION
**Pull request by SimonBin**
I would like to open this for discussion

a relatively small change which is **not** part of the standard

it provides some nice real-world use: you can pass a Geometry literal in a SPARQL query and use the Geo-index to locate some Geometry/Feature, something which is not possible (afaik) to do with a filter(geof:*)

### CODE REVIEW

**Comment by afs** [comment]
GeoSPARQL community - opinions?

Looking at the diff, it seems alright from my perspective but I'm not deeply into jena-geosparql.

It does needs tests and a documentation update.

**Comment by SimonBin** [comment]
Hi @asf 

I added a test case

docs are on the jena-site only? I will prepare a PR

**Comment by afs** [comment]
`s/@asf/@afs/` :smile:

> docs are on the jena-site 

Yes.

**Comment by afs** [comment]
I'm getting a test failure at `SpatialObjectGeometryLiteral.testRetrieve`.

```
java.lang.NullPointerException
	at org.apache.jena.geosparql.geo.topological.SpatialObjectGeometryLiteral.retrieve(SpatialObjectGeometryLiteral.java:107)
	at org.apache.jena.geosparql.geo.topological.SpatialObjectGeometryLiteralTest.testRetrieve(SpatialObjectGeometryLiteralTest.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
. . .
```
The `testRetrieve` argument is null.

Should it be at `SpatialObjectGeometryLiteral:107`?
```
    if (targetSpatialObject != null && 
```
or is there a sync issue because of all the other changes in jena-geosparql recently?

**Comment by SimonBin** [comment]
yes you're right

**Comment by afs** [comment]
Merged (I squashed the commits to one that records the change with a message for the long term)

**Pull request merged**
