### PR TITLE
JENA-1321: Improved error handling so response body is not masked.

### PR DESCRIPTION
**Pull request by rmorrise**

### CODE REVIEW

**Comment by afs** [comment]
To check my understanding: the root problem is that the `QueryExceptionHTTP` does not have the `HttpException.getResponse` available.

`QueryExceptionHTTP` can't be an `HttpException` and `QueryException` (separation of HTTP code from query handling). 

If so, maybe it would be better to add the response body to the `QueryExceptionHTTP` - the removal of the `HttpException` level of exception removes a layer of unhelpful stacktrace (the local source of the `HttpException` is not relevant).  By adding the error response to `QueryExceptionHTTP`, the response would be available still.

**Comment by ajs6f** [comment]
If that understanding is correct (and I now share it) then I agree with @afs's proposal, and I can make that change. @rmorrise ?

**Comment by rmorrise** [comment]
That works.  Personally I prefer to see the original root cause but I guess people sometimes get distracted by long stack traces. If you are going to do that can you check the original exception's hierarchy for other props that might be needed like headers etc.?

**Comment by ajs6f** [comment]
`org.apache.jena.atlas.web.HttpException` only has `getResponseCode()`, `getStatusLine()`, and `getResponse()`. Wouldn't it work to just add those three to `QueryExceptionHTTP`?

**Comment by rmorrise** [comment]
Sounds good. :)

**Comment by ajs6f** [comment]
@rmorrise If you are satisfied with our work on JENA-1321, would you close this?

**Pull request closed without merging**
