### PR TITLE
GH-2344: Yarn fails on windows CI-BUILD

### LINKED ISSUE #2344: `yarn run test:e2e` fails on MS Windows.
The `test:e2e` step of the frontend-maven-plugin in jena-fuseki-ui is not managing to run the tests.

This log is from the projects github action for MS Windows.
```
[INFO] --- frontend-maven-plugin:1.15.0:yarn (yarn run test:e2e) @ jena-fuseki-ui ---
[INFO] Running 'yarn run test:e2e' in C:\jena\jena-fuseki2\jena-fuseki-ui
[INFO] yarn run v1.22.17
[INFO] $ cross-env FUSEKI_PORT="${FUSEKI_PORT:=3030}" PORT="${PORT:=8080}" concurrently --names 'SERVER,CLIENT,TESTS' --prefix-colors 'yellow,blue,green' --success 'first' --kill-others 'yarn run serve:fuseki' 'yarn wait-on http://localhost:${FUSEKI_PORT}/$/ping && yarn run dev' 'yarn wait-on http-get://localhost:${PORT}/index.html && cypress run $@'
[INFO] [CLIENT] 'run' is not recognized as an internal or external command,
[INFO] [CLIENT] operable program or batch file.
[INFO] [TESTS] The filename, directory name, or volume label syntax is incorrect.
[INFO] [TESTS] serve:fuseki exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [CLIENT] run exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [5] 'http:' is not recognized as an internal or external command,
[INFO] [5] operable program or batch file.
[INFO] [5] http://localhost:%FUSEKI_PORT%/$/ping exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [SERVER] yarn exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [3] yarn exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [4] wait-on exited with code 1
[INFO] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error:  There are test failures.
Failed to run task: 'yarn run test:e2e' failed.
```

### PR DESCRIPTION
**Pull request by OyvindLGjesdal**
GitHub issue resolved #2344

Pull request Description:

Looked at the links provided by @kinow in https://github.com/apache/jena/issues/2344#issuecomment-2021290428 and tried to change `'` with `\"`.

This gave a new error which looks like `crossenv` doesn't support `:=` on windows, in `${FUSEKI_PORT:=3030}` (and PORT).
Looked at crossenv on github and I think it is not available.

 I looked at maybe changing the shell to run from in windows, by adding a .npmrc file, but then I got license (RAT) errors when running the CI, and instead of adding it to exclude list, I asked GPT figured the operator is *probably* not available in powershell. I ended up using the ENV vars only since `FUSEKI_PORT` is already used without fallback values in other locations of the package.json file.

Glanced at  the final e2e output in https://github.com/OyvindLGjesdal/jena/actions/runs/8623049304 and it looks good to my untrained eyes.

Have left to check if it breaks anything for Linux and Mac, and will create a single commit.

Output when only fixing the apos -> escaped quote:
```
[INFO] $ cross-env FUSEKI_PORT="${FUSEKI_PORT:=3030}" PORT="${PORT:=8080}" concurrently --names 'SERVER,CLIENT,TESTS' --prefix-colors 'yellow,blue,green' --success 'first' --kill-others "yarn run serve:fuseki" "yarn wait-on http://localhost:${FUSEKI_PORT}/$/ping && yarn run dev" "yarn wait-on http-get://localhost:${PORT}/index.html && cypress run $@"
[INFO] [TESTS] $ C:\jena\jena-fuseki2\jena-fuseki-ui\node_modules\.bin\wait-on http-get://localhost:${PORT:=8080}/index.html
[INFO] [CLIENT] $ C:\jena\jena-fuseki2\jena-fuseki-ui\node_modules\.bin\wait-on http://localhost:${FUSEKI_PORT:=3030}/$/ping
[INFO] [SERVER] $ nodemon src/services/mock/json-server.js
[INFO] [SERVER] [nodemon] 3.1.0
[INFO] [SERVER] [nodemon] to restart at any time, enter `rs`
[INFO] [SERVER] [nodemon] watching path(s): *.*
[INFO] [SERVER] [nodemon] watching extensions: js,mjs,cjs,json
[INFO] [SERVER] [nodemon] starting `node src/services/mock/json-server.js`
[INFO] [SERVER] node:events:496
[INFO] [SERVER]       throw er; // Unhandled 'error' event
[INFO] [SERVER]       ^
[INFO] [SERVER] 
[INFO] [SERVER] Error: listen EACCES: permission denied ${FUSEKI_PORT:=3030}
[INFO] [SERVER]     at Server.setupListenHandle [as _listen2] (node:net:1855:21)
[INFO] [SERVER]     at listenInCluster (node:net:1920:12)
[INFO] [SERVER]     at Server.listen (node:net:2025:5)
[INFO] [SERVER]     at Function.listen (C:\jena\jena-fuseki2\jena-fuseki-ui\node_modules\express\lib\application.js:635:24)
[INFO] [SERVER]     at Object.<anonymous> (C:\jena\jena-fuseki2\jena-fuseki-ui\src\services\mock\json-server.js:294:8)
[INFO] [SERVER]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[INFO] [SERVER]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[INFO] [SERVER]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[INFO] [SERVER]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[INFO] [SERVER]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
[INFO] [SERVER] Emitted 'error' event on Server instance at:
[INFO] [SERVER]     at emitErrorNT (node:net:1899:8)
[INFO] [SERVER]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[INFO] [SERVER]   code: 'EACCES',
[INFO] [SERVER]   errno: -4092,
[INFO] [SERVER]   syscall: 'listen',
[INFO] [SERVER]   address: '${FUSEKI_PORT:=3030}',
[INFO] [SERVER]   port: -1
[INFO] [SERVER] }
[INFO] [SERVER] 
[INFO] [SERVER] Node.js v20.11.0
[INFO] [SERVER] [nodemon] app crashed - waiting for file changes before starting...
```

----
 - [ ] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [ ] Commits have been squashed to remove intermediate development commit messages.
 - [ ] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by afs — DISMISSED** [review]
This looks like an improvement.

I ran before and after Windows jobs (GH actions).
I see `http://localhost:%FUSEKI_PORT%/$/ping` in the breaking "before" which might be due to messing up the substitution and/or quoting  and a lot of stacktraces.

With this PR, the Windows build does not print that nor have stacktraces.

> There are a few more errors after the tests for windows:

(also untrained eyes 🙈 ) Are they errors or is that the test runner clearing up?
With this PR, I see: "All specs passed"  which didn't happen before.

```
[INFO] [TESTS]     ✔  All specs passed!                        00:19       13       13        -        -        -  
[INFO] [TESTS] 
[INFO] [TESTS] yarn wait-on http-get://localhost:%PORT%/index.html && cypress run $@ exited with code 0
[INFO] --> Sending SIGTERM to other processes..
[INFO] [SERVER] yarn run serve:fuseki exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [CLIENT] yarn wait-on http://localhost:%FUSEKI_PORT%/$/ping && yarn run dev exited with code 1
[INFO] Done in 37.36s.
```

**Review by kinow — COMMENTED** [review]
I think this broke the e2e tests on Linux.

```bash
kinow@ranma:~/Development/java/jena/jena/jena-fuseki2/jena-fuseki-ui$ yarn test:e2e
yarn run v1.22.19
$ cross-env FUSEKI_PORT="${FUSEKI_PORT}" PORT="${PORT}" concurrently --names 'SERVER,CLIENT,TESTS' --prefix-colors 'yellow,blue,green' --success 'first' --kill-others "yarn run serve:fuseki" "yarn wait-on http://localhost:${FUSEKI_PORT}/$/ping && yarn run dev" "yarn wait-on http-get://localhost:${PORT}/index.html && cypress run $@"
$ nodemon src/services/mock/json-server.js
$ /home/kinow/Development/java/jena/jena/jena-fuseki2/jena-fuseki-ui/node_modules/.bin/wait-on 'http://localhost:/$/ping'
$ /home/kinow/Development/java/jena/jena/jena-fuseki2/jena-fuseki-ui/node_modules/.bin/wait-on http-get://localhost:/index.html
[SERVER] [nodemon] 3.1.0
[SERVER] [nodemon] to restart at any time, enter `rs`
[SERVER] [nodemon] watching path(s): *.*
[SERVER] [nodemon] watching extensions: js,mjs,cjs,json
[SERVER] [nodemon] starting `node src/services/mock/json-server.js`
[SERVER] JSON Server is running
^C
```

Cancelled after +5 minutes waiting.

Did a `git checkout main`, then re-ran the tests, finished under a minute.

```bash
[TESTS]   (Run Finished)
[TESTS] 
[TESTS] 
[TESTS]        Spec                                              Tests  Passing  Failing  Pending  Skipped  
[TESTS]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[TESTS]   │ ✔  datasets.cy.js                           00:17        9        9        -        -        - │
[TESTS]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[TESTS]   │ ✔  query.cy.js                              00:03        2        2        -        -        - │
[TESTS]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[TESTS]   │ ✔  upload.cy.js                             00:03        2        2        -        -        - │
[TESTS]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[TESTS]     ✔  All specs passed!                        00:24       13       13        -        -        -  
[TESTS] 
[TESTS] yarn wait-on http-get://localhost:${PORT}/index.html && cypress run $@ exited with code 0
--> Sending SIGTERM to other processes..
[SERVER] yarn run serve:fuseki exited with code SIGTERM
--> Sending SIGTERM to other processes..
[CLIENT] yarn wait-on http://localhost:${FUSEKI_PORT}/$/ping && yarn run dev exited with code SIGTERM
Done in 39.73s.
```

I think that's because of the missing default ports?

**Comment by OyvindLGjesdal** [comment]
Added some comments https://github.com/apache/jena/issues/2344#issuecomment-2132421238

**Review by kinow — COMMENTED** [review]
Tested `yarn install`, and ` yarn run test:unit` on Linux, both worked. Then launched `yarn run test:e2e` at 09:30AM.

Nearly 20 minutes later, the process was still stuck on the startup of the JSON server (or some other build step).

image

So I think this breaks the Linux builds...

I will try to boot my old Windows (haven't used it in ages) and see if I can try something to fix yarn on Windows. It's great to have this PR as I can see what you tried already, and then I will see if I can try the same thing with other settings, or try something else altogether.

Cheers

**Comment by kinow** [comment]
Here's `main` on Linux:

```
       -        -        - │
[TESTS]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[TESTS]     ✔  All specs passed!                        00:19       13       13        -        -        -  
[TESTS] 
[TESTS] yarn wait-on http-get://localhost:${PORT}/index.html && cypress run $@ exited with code 0
--> Sending SIGTERM to other processes..
[SERVER] yarn run serve:fuseki exited with code SIGTERM
--> Sending SIGTERM to other processes..
[CLIENT] yarn wait-on http://localhost:${FUSEKI_PORT}/$/ping && yarn run dev exited with code SIGTERM
Done in 35.64s.
```

**Comment by OyvindLGjesdal** [comment]
Is the PR up to date before running? From line 3 in the screenshot, the script should also include the fallback values for the port for nix, which is not present in the image.

```
cross-env FUSEKI_PORT=\"${FUSEKI_PORT:=3030}\" PORT=\"${PORT:=8080}\"
```

for some reason the `:=3030` and `:=8080` part isn't showing.

The logic is that the windows and linux jobs should stay almost the same as before, while there is a different logic for windows.

**Review by afs — APPROVED** [review]

**Pull request merged**
