### PR TITLE
GH-1693: Resizeable query editor

### LINKED ISSUE #1693: Allow the UI query editor to be resized by users
### Version

4.6.0

### Feature

Placeholder for https://github.com/apache/jena/pull/1684

### Are you interested in contributing a solution yourself?

Yes

### PR DESCRIPTION
**Pull request by SimonBin**
GitHub issue resolved #1693

Pull request Description:

a tiny Quality of Live improvement, enable resizeable in the fusekiUI Query editor. That way you can (maybe you still should not!) also view larger queries

test written by @kinow

----

 - [x] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [ ] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Will try to do a quick review on this one (basically just review if we need to change anything else, although I think you found the correct place to update it!).

>Or is there any particular reason why it was disabled?

When I started re-writing the Backbone.js app into a Vue.js app, I tried to keep things as close to what they were before. My plan was to a) migrate the app, b) add unit & e2e tests, c) start working on new features & accessibility & UIUX improvements.

I **think** before the query panel was also not resizeable, so that's why we kept it… the alternative is that I did not notice that it was already resizeable and used some code from the YASGUI docs and forgot to change that flag :smile: 

Thanks @SimonBin !

**Comment by kinow** [comment]
Finally found time to work on this one. Sorry for the delay. Reviewing it now (but will hold on merging as we have ongoing release candidate works)

**Comment by kinow** [comment]
Hi @SimonBin I was going to push to your branch to amend the commit message and add the e2e test, but git said "ERROR: Permission to AKSW/jena.git denied to kinow.". I think you didn't select the option to allow contributors of the project to edit your PR/branch.

Here's the diff for the test. It was fun, I hadn't written a test that required resizing an element yet :slightly_smiling_face: 

```diff
diff --git a/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js b/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
index 0e90435a0c..f8a55e4518 100644
--- a/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
+++ b/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
@@ -76,4 +76,31 @@ describe('Query', () => {
       .its('response')
       .should('have.property', 'statusCode', 203)
   })
+  it('Can resize the query editor', () => {
+    cy.visit('/#/dataset/skosmos/query')
+    cy
+      .get('div.CodeMirror')
+      .should('be.visible')
+      .invoke('css', 'height')
+      .as('beforeHeight')
+    cy
+      .get('div.resizeChip')
+      .should('exist')
+      .trigger('mousedown', {
+        which: 1, force: true
+      })
+      .trigger('mousemove', { which: 1, force: true, x: 0, y: 50 })
+      .trigger('mouseup', {
+        force: true
+      });
+    cy
+      .get('div.CodeMirror')
+      .invoke('css', 'height')
+      .as('afterHeight')
+    cy.get('@beforeHeight').then(beforeHeight => {
+      cy.get('@afterHeight').then(afterHeight => {
+        expect(afterHeight).to.not.equal(beforeHeight)
+      })
+    })
+  })
 })
```

Thanks!

@afs tested locally, small change and works fine. Can be merged now or after 4.7.0 :+1: 

Thanks @SimonBin !

Bruno

**Review by kinow — APPROVED** [review]
Hi @SimonBin I was going to push to your branch to amend the commit message and add the e2e test, but git said "ERROR: Permission to AKSW/jena.git denied to kinow.". I think you didn't select the option to allow contributors of the project to edit your PR/branch.

Here's the diff for the test. It was fun, I hadn't written a test that required resizing an element yet :slightly_smiling_face: 

```diff
diff --git a/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js b/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
index 0e90435a0c..f8a55e4518 100644
--- a/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
+++ b/jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
@@ -76,4 +76,31 @@ describe('Query', () => {
       .its('response')
       .should('have.property', 'statusCode', 203)
   })
+  it('Can resize the query editor', () => {
+    cy.visit('/#/dataset/skosmos/query')
+    cy
+      .get('div.CodeMirror')
+      .should('be.visible')
+      .invoke('css', 'height')
+      .as('beforeHeight')
+    cy
+      .get('div.resizeChip')
+      .should('exist')
+      .trigger('mousedown', {
+        which: 1, force: true
+      })
+      .trigger('mousemove', { which: 1, force: true, x: 0, y: 50 })
+      .trigger('mouseup', {
+        force: true
+      });
+    cy
+      .get('div.CodeMirror')
+      .invoke('css', 'height')
+      .as('afterHeight')
+    cy.get('@beforeHeight').then(beforeHeight => {
+      cy.get('@afterHeight').then(afterHeight => {
+        expect(afterHeight).to.not.equal(beforeHeight)
+      })
+    })
+  })
 })
```

Thanks!

@afs tested locally, small change and works fine. Can be merged now or after 4.7.0 :+1: 

Thanks @SimonBin !

Bruno

**Comment by SimonBin** [comment]
> I think you didn't select the option to allow contributors of the project to edit your PR/branch.

Thanks for the test! I manually added your diff, unfortunately GitHub does not allow maintainer edits for organisation forks...... next time I will create PR from a personal fork, sorry about that

**Review by kinow — APPROVED** [review]
Tested locally.

Ran `yarn run test:unit` and `yarn run test:e2e -- --headless` and both ran successfully!

And TodayILearned about the organization forks thingy. There's always more to learn :slightly_smiling_face: 

Thank you @SimonBin! :+1:

**Review by afs — APPROVED** [review]
When 4.7.0 is formally out ...

**Comment by afs** [comment]
The development flood gates are open ...

**Pull request merged**
