### PR TITLE
Deprecate various API calls

### LINKED ISSUE #1948: Deprecate API operations that may be affected by Jena5.
### Version

4.8.0

### Feature

This is preparation for Jena5 changes by deprecating API calls to features that are "at risk". (Direct use of LiteralLabels, the "well formed" or "isXML" special case for literals).

Discussion also on dev@.

### Are you interested in contributing a solution yourself?

Yes

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #1948

Pull request Description:
This PR deprecates some API features in case they change/go away at Jena5.

There is a lot of "suppress warnings" to keep the code base warning-free.

----

 - [x] Key commit messages start with the issue number (GH-xxxx, or if in JIRA, JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

**Review by kinow — APPROVED** [review]
:+1: to be released with a last 4.x release, and then remove in 5.x?

**Comment by afs** [comment]
4.9.0 may be the last release with a 3-4 month gap.

4.10.0 may be "tidy up last "4.*" for things that accumulate from now till Jena5.

Jena5 isn't until Java21 happens (September 19, 2023) n order to bump to Java17.

All this is a wobbly tower of "maybe" and "as time permits" ... !!

**Comment by kinow** [comment]
Sounds like a good plan, thanks for clarifying!

**Comment by afs** [comment]
Plans have resources, timescales and goals.

Not _a plan_!

**Pull request merged**
