### PR TITLE
JENA-1755: Improve documentation of Query Builders [WIP]

### PR DESCRIPTION
**Pull request by jmkeil**

### CODE REVIEW

**Comment by jmkeil** [comment]
Improved JavaDoc for `ExprFactory` and `UpdateBuilder` is still missing.

**Comment by Claudenw** [comment]
The changes are fine but I think that there might need to be more documentation in the package info describing things like how to get a ExprFactory and providing examples of how to use it.

**Comment by afs** [comment]
@Claudenw - The 3.13.0 release approaches.

Is this ready to merge, and then add to package info later, or not merge and wait until there is a complete set of documentation upgrades?

If "ready to merge" could you, as reviewer, approve it, and ideally merge it?

**Comment by afs** [comment]
Thanks. JENA-1755 is still open to track any further changes.

**Pull request merged**
