### PR TITLE
JENA-1517: Implement missing override in OpVarsPattern visitor

### PR DESCRIPTION
**Pull request by jeremy-coulon**

### CODE REVIEW

**Comment by rvesse** [comment]
+1

**Comment by jeremy-coulon** [comment]
I will try to add a unit test in order to make sure that MINUS actually works with OpQuadBlock.

**Comment by jeremy-coulon** [comment]
It seems that I fixed the MINUS queries but FILTER EXISTS/NOT EXISTS are still not working.

**Comment by jeremy-coulon** [comment]
EXISTS/NOT EXISTS UTs are working. I probably have another bug in my application.

**Pull request merged**
