### PR TITLE
GH-1272: Use static in-scope base for IRI()

### PR DESCRIPTION
**Pull request by afs**
Static scoped base for IRI("<x>").

### CODE REVIEW

**Comment by afs** [comment]
There is one wrinkle to sort out. SSE parsers in two steps: text to general expression and general expression to update.

There is compatibility code in the PR.

Ideally, `(iri ...)` would take a new, optional arg to be the base. That said, SSE+updates isn't very common and SSE is primarily for Jena-dev use, it's just grown / been spotted.

**Comment by Aklakan** [comment]
Just a minor remark: E_URI should have a public getBase() method so it can be accessed during expression traversal.

**Comment by afs** [comment]
> Just a minor remark: E_IRI should have a public getBase() method

yes, and more! The second commit add a 2-argument form `IRI(baseExpr, rel)`. For update, I think that this general form might be useful for translating data. Experimental.

That'll need accessors to the state of E_IRI that "ExprFunction1" does not expose for printing (to SSE and to SPARQL) - WIP.

Whether it is better to be an "ExprFunction2" or "ExprFunctionN" isn't clear. `IRI` is still primarily a one-argument function. because it retains how it was setup (implicit base or explicit base), it isn't a true "ExprFunction2" either.

(And some of this code structure is really old!)

**Comment by afs** [comment]
There are now 2 IRI functions: the standard "E_IRI" takes on argument and records the pasrer base and "E_IRI2" which has two arguments - `(base, rel)` - and because `base` can be relative, it also records the parser base.

These become functions `(iri)` and `(iri2)`.

**Pull request merged**
