### PR TITLE
GH-1749: Replacing webpack chunks by Vite rollup

### LINKED ISSUE #1749: Fuseki UI sometimes doesn't load
### Version

4.8.0-SNAPSHOT

### What happened?

I apologise for this very vague bug report. I also don't expect any action, I just want to write it down in case someone can add more details.

The issue is as follows: sometimes the fuseki Query UI does not load. To reproduce it (fairly frequently) on our installation, I used a link like this:

```
https://XXXXXXXXXXXX/#/dataset/YYYYYYYYYYYY/query?query=PREFIX%20units%3A%20%3Chttp%3A%2F%2Fwww.opengis.net%2Fdef%2Fuom%2FOGC%2F1.0%2F%3E%0APREFIX%20geo%3A%20%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20spatial%3A%20%3Chttp%3A%2F%2Fjena.apache.org%2Fspatial%23%3E%0A%0Aselect%20distinct%20%3Ffeature%20%3Ftype%20%3FxgeoL%20%7B%0A%20%20values%20%3FmyPoint%20%7B%0A%20%20%20%20%22Point%2822.83736%2033.38213%29%22%5E%5Egeo%3AwktLiteral%0A%20%20%7D%0A%20%20%3Ffeature%20spatial%3AnearbyGeom%28%3FmyPoint%20100%20units%3Akilometre%29%20.%0A%20%20%3Ffeature%20rdfs%3Alabel%20%3FxgeoL%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20a%20%3Ftype%20.%0A%7D
```

put it on a website and opened it in private window mode

Then, the browser would only render the fuseki header (datasets/manage/help/server status green) and the rest of the page would not load (show as blank page). the browser would continue to show the loading indicator

In the Developer Tools, I could observe an unhandled/unconsumed request for Query-abcdef.js that was hanging there

I found a bug report which sounds similar https://github.com/storybookjs/builder-vite/issues/439

I reverted back to webpack on our custom installation for the time being

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

None

### PR DESCRIPTION
**Pull request by kinow**
GitHub issue resolved #1749

Pull request Description:

The [vue docs for layz loading routes](https://router.vuejs.org/guide/advanced/lazy-loading.html) shows an example of webpack and vite for dynamic lazy imports of routes.

We had webpack before moving to Vite, but we did not update this part. This shouldn't be breaking anything, but could be related to #1749.

It will be marked as a draft until we can figure out if this fixes #1749 or not, or otherwise add another commit with the fix for that issue here.

----

 - [ ] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SimonBin** [comment]
ERROR: Permission to kinow/jena.git denied to SimonBin.

```
commit 3acc8c2a331877c3b6c887b82fb8ec19998ccfa1
Author: Simon Bin <sbin@informatik.uni-leipzig.de>
Date:   Mon Apr 17 10:04:30 2023 +0200

    fix vite paths

diff --git a/jena-fuseki2/jena-fuseki-ui/vite.config.js b/jena-fuseki2/jena-fuseki-ui/vite.config.js
index 4df3544a29..828d6ad4e4 100644
--- a/jena-fuseki2/jena-fuseki-ui/vite.config.js
+++ b/jena-fuseki2/jena-fuseki-ui/vite.config.js
@@ -58,18 +58,18 @@ export default defineConfig({
       output: {
         manualChunks: {
           'queryDataset': [
-            '../views/manage/ExistingDatasets.vue',
-            '../views/dataset/Query.vue'
+            'src/views/manage/ExistingDatasets.vue',
+            'src/views/dataset/Query.vue'
           ],
           'manageDataset': [
-            '../views/manage/NewDataset.vue',
-            '../views/dataset/Upload.vue',
-            '../views/dataset/Edit.vue',
-            '../views/dataset/Info.vue'
+            'src/views/manage/NewDataset.vue',
+            'src/views/dataset/Upload.vue',
+            'src/views/dataset/Edit.vue',
+            'src/views/dataset/Info.vue'
           ],
           'other': [
-            '../views/manage/Tasks.vue',
-            '../views/Help.vue'
+            'src/views/manage/Tasks.vue',
+            'src/views/Help.vue'
           ]
         }
       }
```

**Comment by kinow** [comment]
Ha! I looked at those two side by side, comparing, and I swear I couldn't find any difference. But now it's very clear :laughing: :eyeglasses: thanks @SimonBin , I'll update the PR.

**Comment by SimonBin** [comment]
:+1:  from me, #1749 didn't happen after I merged this

**Comment by afs** [comment]
How safe is this fix?

If, as looks likely, 4.8.0 RC2 is needed, what are the risks?

**Comment by kinow** [comment]
> How safe is this fix?
> 
> If, as looks likely, 4.8.0 RC2 is needed, what are the risks?

I can do some manual testing. Plus, e2e tests would fail if this change borked — it involves creating chunks to be loaded lazily, and the same mechanism is used for all chunks, including query view; if that were broken, users would get a blank screen and console errors.

So worst case users would see that blank screen with a JS error, but no corrupted data nor any server side errors :slightly_smiling_face: But this should be easy to test by testing on different browsers (I have a Windows machine to test too) & running the e2e tests.

**Comment by kinow** [comment]
Rebased, now testing it.

**Comment by kinow** [comment]
Well, good news is that the build succeeded with Maven, all unit tests pass, manual tests found no issues, and running Cypress manually (`npx cypress open` and then running each test suite) worked.

Running Cypress e2e tests automatically, with `yarn run test:e2e` is the only think broken. We use a library, cypress-vite, that appears to be doing something else with rollup and/or vite, and failing to launch the e2e tests.

Will take a better look tomorrow/later.

**Review by kinow — COMMENTED** [review]
@SimonBin I've finished testing it. I had to modify the Cypress configuration (for e2e testing) so that the e2e tests would still pass in the command-line.

I've tested manually, and automatically, on Ubuntu LTS and Firefox 112, running locally on Eclipse + WebStorm.

Could you re-test it, please, and share your environment settings too? We **may** be able to squeeze it in the 4.8.0 RC2 (no promises), but it'd be easier if we can get more people testing and in different environments. I have a Windows VM at work that I will try to use tomorrow if I manage to find some time between meetings/trainings.

Cheers
-B

**Comment by kinow** [comment]
For the test, please confirm that it fixes the #1749 but also try to navigate to other views/pages and report if you find anything that was working and is now broken. Thanks!

**Comment by afs** [comment]
I tried the branch here and the build+run works so let's merge it for 4.8.0 RC2. It seems that the risk is that the original problem is not fully addressed by this final form.

**Comment by kinow** [comment]
>I tried the branch here and the build+run works so let's merge it for 4.8.0 RC2. It seems that the risk is that the original problem is not fully addressed by this final form.

True. @SimonBin can confirm if 4.8.0 works on his environment without problems :+1: 

Thanks Andy!

**Comment by SimonBin** [comment]
Hi, we're already running 4.8.0 with this patch no issues so far

**Comment by kinow** [comment]
> Hi, we're already running 4.8.0 with this patch no issues so far
4.8.0 from the vote/pre-release branch? Or 4.7.0 with this patch?

**Comment by afs** [comment]
There is now an RC2 release candidate which includes this.

**Pull request merged**
