### PR TITLE
speed up GenericSpatialPropertyFunction with more efficient iter usage

### PR DESCRIPTION
**Pull request by SimonBin**
original code by @LorenzBuehmann

we found two issues

1) a LIMIT on the query is not transparently respected by SPF, as all results are first wrapped
2) the closing of unconsumed QueryIterPlainWrappers stalls Jena for an extended period of time

### CODE REVIEW

**Comment by afs** [comment]
> original code by @LorenzBuehmann

Thank you for putting that in. It is very important.

Could you expand on that statement? Is it referring to the original code this PR is changing or the code in the PR itself?

If the latter, if @LorenzBuehmann is the owner, then they should submit it.
(Who is the IP owner for code in SANSA-Stack?)

We can not accept code from a 3rd party unless the license of the original code allows it, and even then, the preference is not to take code but to receive it from the original author. That way, the IP situation is clear.

**Review by afs — CHANGES_REQUESTED** [review]
Claritiy requested about the the IP situation.

**Comment by LorenzBuehmann** [comment]
Hi @afs , it's fine - we're working in the same research group, @SimonBin just kindly cleaned up my initial code base and opened a new branch just containing the minimal changes addressing the issue. The PR is based on just the relevant code. Sorry for confusion.

**Comment by LorenzBuehmann** [comment]
### Update we moved the whole Apache Jena fork to our research group AKSW - we wanted to do this anyways.

**Comment by afs** [comment]
I'm not so worried about the repo and you have a ICLA on file.

Who owns the IP and copyright of code produced by the research group?

Bug fixes and "small, obvious" things aren't IP issues but there are now several substantial contributions, which is great.

If it is AKSW who owns the IP.copyright, then maybe an CCLA (it has named contributors) is simplest so that things are completely clear now, and there are no questions later.

**Comment by LorenzBuehmann** [comment]
Meh, not sure about the legal status of AKSW nowadays - it was our former research group at University of Leipzig, technically our employer is different. Let me re-create the PR from my own account such that I'm not wasting your time and speed things up. Sorry for confusion.
Feel free to close this PR please

**Pull request closed without merging**
