### PR TITLE
GH-2462: Fuseki reload configuration

### LINKED ISSUE #2462: [Fuseki] Reloadable configuration files
### Version

5.0.0 dev

### Feature

Add a server action that reloads the services defined in a configuration file and replace the server data services configuration with zero-downtime, no HTTP request lost or aborted while the server is running.

This allows:

1. Reloading an in-memory graph with data from a file.
2. Change the location of a TDB2 database
3. Change of database configuration (e.g. (re)setting per dataset or per-endpoint query timeouts)

This is a subset of the configuration file capabilities. Some changes still require a server restart.

Limitation: transient data (in-memory, data loaded via HTTP) may be lost.

### Are you interested in contributing a solution yourself?

Yes

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #2462

Pull request Description: Provide reload of the config.ttl with zero interruption of service.

+ some clean-up done while working on this PR.
The logging support code changes better isolate the logging implementation specific functions.

----

 - [x] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Code is looking good! Had a quick go-through and found nothing that seemed wrong.

Any plans to expose it in the UI too, @afs? Like the backup/delete actions, in the management part of the UI? Or will it be only available if the user or admin prepares the request and runs it directly from command-line or some other HTTP client?

**Comment by namedgraph** [comment]
Is this available in `jena-fuseki-main`?

**Comment by namedgraph** [comment]
And can this feature be used to add new datasets?

**Comment by afs** [comment]
> Any plans to expose it in the UI too, @afs? Like the backup/delete actions, in the management part of the UI? Or will it be only available if the user or admin prepares the request and runs it directly from command-line or some other HTTP client?

This discussion is showing that this is a big area. This PR isn't as grand as that.
It would be good to have admin UI to be able to do this.

That would be a reason to split the UI in two - admin and workbench. But again we can have big plans and we need tio have a way to creep up on them.

**Comment by afs** [comment]
> Is this available in `jena-fuseki-main`?

This PR is open and not finished. The commit log for the codebase shows what's available.

> And can this feature be used to add new datasets?

Yes - but not all types of datasets can be guaranted. Assemblers are too general.

**Pull request closed without merging**
