### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by nirajpatel**

### CODE REVIEW

**Comment by ajs6f** [comment]
I'm not sure that our `README` actually _is_ Markdown. Is there a reason you would particularly like to see this file ending? Perhaps some further integration?

**Comment by nirajpatel** [comment]
The only reasoning behind renaming is to have it render nicely in the GitHub UI and IntelliJ

Before:
https://github.com/apache/jena/blob/master/README

After: https://github.com/apache/jena/blob/5f6fd0cb710420ce17e87c28236bbfa056a485e3/README.md

**Comment by ajs6f** [comment]
That does look more pleasant! I'll wait a few days in case there's some reason this is a bad idea that I'm not seeing, and then I'll merge. Thanks for the contribution @nirajpatel !

**Comment by afs** [comment]
@nirajpatel  - done - thanks!

**Pull request merged**
