### PR TITLE
JENA-1757: Deprecate GraphStatisticsHandler

### PR DESCRIPTION
**Pull request by afs**
Illustration of deprecating `GraphStatisticsHandler`, not for merging in the current state.

This does the work for src/main/java.  It does not touch very much.

There are still warnings in the jena-core test code and the way forward is probably to remove the tests.

### CODE REVIEW

**Comment by afs** [comment]
Second commit does the removal of the tests for graph statistics handler.  They are for graph-mem and union graph when the components are all graph-mem.

**Comment by Claudenw** [comment]
I think there are deprecation annotations missing from permissions code.
But I am traveling and can not check.

**Comment by afs** [comment]
No problem - I'll take care of it.

**Comment by afs** [comment]
Done and added the second commit - just a couple of uses.

**Pull request merged**
