### PR TITLE
update lucene version to 9.4.1,  migrate lucene-analyzers-common to l…

### PR DESCRIPTION
**Pull request by OyvindLGjesdal**
…ucene-analysis-common

GitHub issue resolved (#1581 WIP)

Pull request Description:

----

 - [ ] Tests are included.
 - [x] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by kinow — APPROVED** [review]

**Comment by kinow** [comment]
Ref: https://lucene.apache.org/core/9_0_0/MIGRATE.html

**Comment by afs** [comment]
Discussion regarding managing a Lucene upgrade on the companion issue #1581.

**Review by afs — APPROVED** [review]

**Comment by OyvindLGjesdal** [comment]
I'll squash to a single commit and start the commit message with GH-1581

**Comment by OyvindLGjesdal** [comment]
There was a new minor release on with one bug fix specific for 9.4.0.

See https://lucene.apache.org/core/9_4_1/changes/Changes.html for full notes

```
When reading large segments, the kNN vectors format could fail with a validation error, preventing further writes or searches on the index. This bug is now fixed. Only version 9.4.0 was affected, so it is recommended to skip 9.4.0 if you are using kNN vectors.
```

**Pull request merged**
